### ISSUE TITLE
Building applications with electron-packager results in an error

### ISSUE THREAD

**Issue by alexanderturinske** [castlabs/electron-releases#11]
# Context
 - Electron version: `v1.8.7-hpcp-vmp1010`
 - Operating system: MacOS High Sierra
 - Node version: v6.13
- [electron-packager](https://github.com/electron-userland/electron-packager) `12.0.1` to build the Mac application (I see electron-release is using `"^3.0.1"`)
- [electron-winstaller](https://github.com/electron/windows-installer) to build the Win application

# Questions
1. Do I need to build the unsigned version of my application with castlabs/electron-releases? 
2. Can I build the unsigned version of my app with electron/electron and then sign it using the script provided by castlabs/electron-releases?
3. What is the recommended way to build the unsigned versions of the app? Or documentation regarding it?

# What I have tried
- I tried building with `electron: "1.8.7"`, but then when I run your python script, it completes without an error and without creating signed applications
- When I try to build the unsigned applications with  `v1.8.7-hpcp-vmp1010`, electron-packager fails with an error because it creates the wrong url `Downloading tmp-13310-0-electron-v1.8.7-hdcp-vmp1010-win32-x64.zip
Error: GET https://github.com/electron/electron/releases/download/v1.8.7-hdcp-vmp1010/electron-v1.8.7-hdcp-vmp1010-win32-x64.zip returned 404`. This is obviously the wrong url.
- I am debugging into electron-packager, but I thought I would ask in parallel to doing that
EDIT:
- Ah, `get baseUrl () {
    return process.env.NPM_CONFIG_ELECTRON_MIRROR ||
      process.env.npm_config_electron_mirror ||
      process.env.ELECTRON_MIRROR ||
      this.opts.mirror ||
      'https://github.com/electron/electron/releases/download/v'
  }`, environment variables to change where the download comes from.

# Updates
- Got the app building with ` "electron": "https://github.com/castlabs/electron-releases#v1.8.7-hdcp-vmp1010"` with electron-packager by setting one of those environment variables (`export NPM_CONFIG_ELECTRON_MIRROR=https://github.com/castlabs/electron-releases/releases/download/v`
- the signing only works for the Window `.exe`s because `electron-packager` chose to download `https://github.com/castlabs/electron-releases/releases/download/v1.8.7-hdcp-vmp1010/electron-v1.8.7-hdcp-vmp1010-win32-ia32.zip'` and not the `darwin` one, so now I am debugging that
- the signing creates a `.sig` file, which I assume is going to get picked up by `Widevine` in the application by the `.sig` being in the same folder as the `.exe`, is that correct?
- Writing this all here to help future engineers

**Comment by khwaaj** [comment]
Hi Alexander,

Looks like you have progressed a bit, but I'll start by answering trying to answer your questions:

1. Not exactly sure what you mean here, or what your goal is, but if you need Widevine support the regular stock Electron does not provide it out of the box, so I think the answer would be "Yes" here, especially if you need or want VMP support. 

2. No, like I mentioned in (1), regular Electron does not provide Widevine support without manually installing a Widevine CDM, which makes just signing it pointless. Even with a manual CDM installation there are other aspects of VMP that need to be fulfilled that stock Electron does not, this is part of the value the castLabs Electron releases bring to the table.

3. There is really no point in building an unsigned app if you need playback of Widevine protected content to work. Depending on the configuration of the Widevine DRM servers that are contacted to request content licenses, the requests are likely to be denied if the signature is missing or invalid.

---

About electron-packager I see that you are on the right track. Setting the mirror is a requirement to work with customized releases, but it can also be done in package.json, instead of as an environment variable, if you want to keep all then configuration in one place.

The castLabs Electron releases are pre-signed for development purposes, so as long as the signatures are not broken, as they are prone to be by the metadata added by packagers on Windows, playback will work against any Widevine DRM server that accepts development clients. To be able to re-sign broken packages you need to have a free license agreement with Widevine and get your own VMP certificates to use with the re-sign script. Since you mention you are experimenting with re-signing the final package you may already be aware of this, otherwise it is described in the [README](https://github.com/castlabs/electron-releases/blob/master/README.md).

As you guessed, the .sig files that are part of the releases are re-generated by the re-sign script and automatically picked up and verified by Electron and the Widevine CDM. On Windows the .sig file resides next to the .exe file, but in later releases on macOS it has moved further into the app bundle.

You should check out issue #8, the conversation in there may be of interest to you as it covers some of the same topics.

**Comment by alexanderturinske** [comment]
Thank you for such a thorough response! I really appreciate it! You answered my questions excellently and I understand more now!

**Setting the mirror**
Ah yes, right at the end there is `this.opts.mirror`. It is also described in [the docs](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#download). Thanks; putting all my configurations together is definitely something I want to do. Reading issue #8 helped confirm that.

**VMP certificates**
Yes; it was a long time of waiting to get the certificates, but I got them. I got a part of it as a `.der`, but your example uses a `.pem`; it does not seem hard to convert using `openssl` (`openssl x509 -in cert.der -inform der -outform pem -out cert.pem` is the command I used), but the script seems agnostic in the certification file type; is that correct?

**Comment by khwaaj** [comment]
Happy to be of help. The re-sign script works with either DER or PEM formatted files, for both the key and certificate, but if you want to convert them you can certainly use ```openssl``` to do it, like you suggest.

**Comment by alexanderturinske** [comment]
Got it working locally! Success! Teamwork makes the dream work!

Out of curiosity, (and out of the scope of the original ticket) do you have plans to release a version of this package for electron v2.0.3?

**Comment by khwaaj** [comment]
Great news!

The way things stand we will not release a 2.x version, but will jump directly to 3.x to be able to use some updates available in later versions of Chromium.

**Comment by alexanderturinske** [comment]
So, basically this npm package includes everything that Electron's Widevine CDM Plugin page says one needs as well as including all the infrastructure for app-signing, correct? Thus we do not need to do any of the Widevine CDM Plugin stuff?

If that is so, in the Widevine CDM Plugin docs, it says "Electron doesn't ship with the Widevine CDM plugin for license reasons", how did y'all get around that?

**Comment by khwaaj** [comment]
Exactly, no need to do any of the steps for the Widevine CDM that is in the stock Electron documentation.

Firstly, we are not actually shipping the Widevine CDM with the package since there are some restrictions regarding that, but it is dynamically installed on first launch. Secondly, castLabs and Google Widevine are cooperating on this project.

**Comment by alexanderturinske** [comment]
Certificate question; I received the certificates and what-not from google and there is a prod one and a dev one. What are the differences between the two (i.e. what makes the dev one not suitable for prod)?

**Comment by khwaaj** [comment]
The difference is that the dev certificate will only work with UAT Widevine servers or servers that explicitly allow development clients. The purpose is to limit access to the prod certificate by allowing the daily development to take place without it, and only releases to be prod signed.

The Electron binary we provide as part of our releases is pre-signed with a dev certificate, a restriction placed on us by Widevine, which is part of the reason each app developer needs their own agreement (the other part being that some scenarios break the signature during packaging of the app, especially on Windows).

**Comment by alexanderturinske** [comment]
I forgot to mention that I totally got this working for production and it is rad! Thank you so much for all of your help!

I have a question about a note in the README, `NOTE: Make sure to use the vmp-resign.py tool corresponding to the release in use. If Electron is installed as a node module, using npm, the correct script is available in node_modules/electron/vmp-resign.py.`, which sounds like the python script is version specific (1.8.7 vs 1.8.1) but looking at the python script, I do not see many commits relating to versioning of the script and besides that, all of your releases are for v1.8.x, which all use the same version of Chromium, so I was wondering what that meant. Does that mean that someone could not try to jump ahead to v2.0.0 with your python script?

**Comment by khwaaj** [comment]
No, problem, glad it is working out for you!

This note is just a caution that the tool connected to a particular release-version should be used with that release. It has happened in the past that breaking changes have been made to this script, which would have given incorrect results if the wrong version of the script was used (on macOS only, so far IIRC). Using this script with a stock electron 2.0.x wouldn't do much good. It would generate the required signatures, sure, but since stock electron lacks the changes we have made to support VMP and Widevine installation it would not work.

**Comment by alexanderturinske** [comment]
Thanks! 

The reason I ask is that we are seeing some video stuttering and are attempting to solve the solution on multiple fronts, one of which would be to update the version of electron to >= v2.0.x as there seems to several commits that fix GPU issues, hardware acceleration issues, and the addition of some flags to disable just the GPU. As you have mentioned previously, y'all are not planning a v2.0.x release, but are instead going to do a v3.0.x release, which is not out yet, so I tried to jump ahead...unsuccessfully. 😛 

Any idea when your new v3.0.x release would be? Probably sometime after electron moves it out of beta, eh?

**Comment by khwaaj** [comment]
That sound ominous, are you seeing this under some specific circumstances or on specific hardware?

The 3.0.x update is currently a work in progress and it is possible that we will release a beta version before it goes stable. I can't promise any dates at this point though, but I'm hoping to have something published by the end of August.

**Comment by alexanderturinske** [comment]
It happens mainly on older Macbook Airs, but we seem to have narrowed down the issue to be caused by some unoptimized Angular code, so we are good for now. Thank you.

Thanks for the heads up; we will definitely be keeping an eye out for that upgrade. 👀
