### ISSUE TITLE
CreateCdmFunc not available on signed mac application

### ISSUE THREAD

**Issue by vaukalak** [castlabs/electron-releases#110]
I'm using this electron fork, and playback works fine when I run in the dev mode. When I sign the application, I got the `widevine-ready` event, and the application starts. But on playback attempt I got the following error: 

```
Kr {code: 5, message: "Failed to execute 'createMediaKeys' on 'MediaKeySystemAccess': CreateCdmFunc not available."}
```

I'm signing the app via the following command:
```
python3 -m castlabs_evs.vmp sign-pkg [path-to-unsigned-electron-app]
```
this happens before apple notarization stage.

The terminal output I get is:
```
 - Verifying existing VMP signature
 - Signature invalid: Certificate is valid for development only
 - Requesting VMP signature
 ```

**Comment by khwaaj** [comment]
I can't say for sure what the cause is without some more details. A few questions:
 - What platform/architecture is this, and what version of ECS?
 - Is the signing script executed synchronously and actually returning? What is the return code?
 - What is the output if you try to execute `python3 -m castlabs_evs.vmp verify-pkg [path]` on the final application?

**Comment by natehudson** [comment]
Thanks for the prompt response @khwaaj  
I'm working with @vaukalak on this problem and can answer those questions.

- We are building and signing on a Mac `x86_64` running OS X `10.15.7` and using ECS version `12.2.0-wvvmp` trying to package for windows and mac. Our windows playback is working but the mac one is hitting the `CreateCdmFunc not available."}
` error

- We are VMP signing the Mac binary with `await exec('python3 -m castlabs_evs.vmp sign-pkg ' + params.appOutDir )` in the electron-builder `afterPack` hook script and I believe it is returning a good return code but have not verified.

- The verify package looks good:
```
Verifying signature for: dist/mac/[our app].app
 - Signature is valid [streaming, 3205 days of validity]
```

I just noticed that we have a `devDependencies` of `v15.0.0-wvvmp` instead of the `12.2.0-wvvmp` for release packaging so that might explain something on our end. We are going to try and upgrade.
