### ISSUE TITLE
widevine-error Download error: 404 

### ISSUE THREAD

**Issue by andymartinwork** [castlabs/electron-releases#127]
After updating from electron version 13.6.7-wvvmp to 13.6.9-wvvmp we have started to get this message through. It only seems to affect windows, and affects over 100 users at the moment. The error means that the users cannot stream widevine content even after closing and opening the app.

Given that there doesn't seem to be a way to debug widevine errors, I wonder if you can shed some light on how this could happen? I guess google's windows widevine assets haven't been moved?

**Comment by khwaaj** [comment]
Looks like there is some issue on the Widevine side where the asset for `4.10.2449.0-win-ia32.zip` is missing from the server. This CDM was just released this week so something probably went wrong when they published it. I've reported it to Widevine, so hopefully it will be fixed promptly.

In the mean time the x64 asset seems ok, so if your users are capable of running the x64 version of the app that should work. Other options are to start experimenting with [the `versionPattern` option](https://github.com/castlabs/electron-releases/issues/39#issuecomment-511734695), or updating to a more recent version of ECS that is using the Component Updater (v16 and above), although both these options would require you to publish a new release.

**Comment by sudharsans85** [comment]
We are stuck with same error in 32bit application. In our case, we have a controlled distribution. Is there any possibility of making it work by copying the missing asset 4.10.2449.0-win-ia32.zip or equivalent manually from a system where it had worked earlier? If yes, please let us know the steps

**Comment by khwaaj** [comment]
If you are able to prepare installations you can manually extract a working zip into the relevant path and ECS will pick it up automatically when it is started/relaunched. On Windows this path is typically something like `$HOME/AppData/Roaming/$YOUR_APPLICATION_NAME/WidevineCDM`.

The currently latest working `ia32` version can be found here:

https://redirector.gvt1.com/edgedl/widevine-cdm/4.10.2391.0-win-ia32.zip

And the result should look something like this:

```
WidevineCDM
├── LICENSE.txt
├── manifest.json
├── widevinecdm.dll
├── widevinecdm.dll.lib
└── widevinecdm.dll.sig
```

Note that this is for the `wvvmp` builds only - not `wvcus` where things work a bit differently since it uses the Component Updater.

**Comment by sudharsans85** [comment]
Thanks @khwaaj , we are using wvvmp build, so this solution seems to work fine. Will check further & use this as temporary solution. Will there be any issue in case of CDM update - if it identifies there is update, but the artifact is missing - Is there anything we can/should do about it. 

Please let us know once widevine team gets back to you about the missing asset - when it ll be restored. 
I know 32bit CDM was deprecated for linux, is Widevine team planning to do the same for Windows also - am not sure about marketshare of users still with 32bit windows - but i assume its higher compared to that of linux 32bit

**Comment by khwaaj** [comment]
ECS will still check for updates, and in this case try to download it since there is an update available according to the information it has. Failures during update is not fatal though, so unless something is wrong they should not affect usability.

Sure, I actually found out that the asset was accidentally published using `x86` for the architecture instead of `ia32`, so it is available - just under the wrong name. I've not heard anything back since then though so I'm not sure when it will be fixed. And as far as I know there are no plans to deprecate `win-ia32` anytime soon.

**Comment by khwaaj** [comment]
I forgot to add that if it turns out to be an issue [updates can be disabled](https://github.com/castlabs/electron-releases/tree/15-x-y#widevine-cdm-installation).

**Comment by andymartinwork** [comment]
It doesn't seem to have been fixed yet. We don't want to switch to x64 as it doesn't run on ARM based windows.
I think bundling the files seem to be the only option for now. I will work on that and listen here for news that it will be fixed.

**Comment by andymartinwork** [comment]
It seems that this sort of solution works technically, but I'm not totally sure about the licensing / legal implications of the fix?

https://en.wikipedia.org/wiki/Widevine#Criticism

Someone who had previously tried to bundle the widevine binaries with the application had their licence denied. I'm a bit worried that could affect the application I work on.

In that case, it seems we are between a rock and a hard place. Not able to legally bundle widevine, but widevine themselves pointing to a broken URL.

**Comment by khwaaj** [comment]
The ECS project was created in response to that criticism and we're authorized to support it, with all Google Widevine licenses in place. The solutions proposed above are unfortunately the only paths available until Google fixes the download server.

However, there are potentially other legal implications due to the h264 decoder in the CDM which may or may not incur MPEG-LA royalties when bundled, as touched on in this [FAQ entry](https://github.com/castlabs/electron-releases/wiki/FAQ#can-i-bundle-the-widevine-cdm-to-avoid-downloading-it-on-first-start). We can't provide legal advice, but it is something to consider...

**Comment by andymartinwork** [comment]
That version string worked nicely, thank you very much!
How creative to come up with a negative lookbehind regex. I must add that to my repertoire.
I must remember to remove it when widevine increases the version beyond 4.10.

**Comment by khwaaj** [comment]
When Widevine moves beyond 4.10 the API interface version will have changed and none of the current ECS releases will support it anyway, so I think you are safe there for the time being.

Version 11 of the API interface is not yet stable, but even if it is released tomorrow they would typically keep the previous version alive for some time before deprecating it.

**Comment by khwaaj** [comment]
Version 4.10.2449.0 is now fixed for win-ia32 on Google servers and should work fine to use again.

A heads up though. Google is planning to deprecate the old HTTP delivery mechanism, Lorry, at some point and only deliver CDMs through the Component Updater. I don't have the exact timeline, but it should be kept alive at least until Q3 this year. At that point the last version of ECS using Lorry, v15, will be unsupported and only versions using Component Updater should be used (i.e. v16 and later).

**Comment by andymartinwork** [comment]
I've confirmed that the 404 error is fixed.

The versionPattern fix worked but occasionally resulted in these errors for users:
["Shaka: Error", "FAILED_TO_CREATE_CDM (6002)", undefined]
["Shaka: Error details", ["Failed to execute 'createMediaKeys' on 'MediaKeySystemAccess': CreateCdmFunc not available."]]

I've managed to reproduce the error by starting the app several times. It seems to happen infrequently and is fixed with a restart. I think the plugin might be getting confused when attempting to download a widevine update sometimes.

I think I will remove the versionPattern fix and rely on the latest Widevine fix again.

**Comment by khwaaj** [comment]
> The versionPattern fix worked but occasionally resulted in these errors for users:
["Shaka: Error", "FAILED_TO_CREATE_CDM (6002)", undefined]
["Shaka: Error details", ["Failed to execute 'createMediaKeys' on 'MediaKeySystemAccess': CreateCdmFunc not available."]]
>
> I've managed to reproduce the error by starting the app several times. It seems to happen infrequently and is fixed with a restart. I think the plugin might be getting confused when attempting to download a widevine update sometimes.

Hm, that looks like the CDM isn't properly loaded before the BrowserWindow is created. Did you by any chance create the BrowserWindows on `ready` instead of `widevine-ready` after calling `app.verifyWidevineCdm()`? Not that it matters in this case anymore, but I'm curious to see if there is a real issue behind it.

**Comment by andymartinwork** [comment]
Yes, that does seem to be the case. The BrowserWindow is created on `ready` rather than `widevine-ready`.

**Comment by khwaaj** [comment]
For the record Google will move to using `x86` instead of `ia32` permanently on Lorry until it is deprecated. To deal with this situation we've just published [v15.5.4-wvvmp.1](https://github.com/castlabs/electron-releases/releases/tag/v15.5.4-wvvmp.1), which contains support for architecture aliases when downloading the CDM.

⚠️ Beware that this fix will not be coming to unsupported version of ECS, i.e. any release before `v15`. If you are using older version and need to support `win-ia32` we suggest looking at an upgrade path to `v15` near term. Longer term you should look at moving to a release using the Component Updater, i.e. `v16+`.

**Comment by andymartinwork** [comment]
We're currently in the process of upgrading to electron 15 (and then of course to the current version(, but it's taking time due to the remote module being removed involving a refactor.

What would your advice be for the clients outside the supported versions? To use versionPattern to lock onto the current version until it's possible to move to 15?

**Comment by khwaaj** [comment]
Yeah, that is the only recourse I can see. But it will stop working once Widevine revokes that version of the CDM, which could be anytime (depending on possible vulnerabilities and so on).

**Comment by andymartinwork** [comment]
We updated to Electron 15 with the fix, but it appears a lot of our users (me included) had their DRM broken.
I understand 15 is no longer supported, and I am moving to the latest version of Electron, but perhaps something may have been wrong with the fix? Since it was working on electron 13 for now.

**Comment by khwaaj** [comment]
I cannot reproduce this, so I need some more specific information if we are to be able to figure out what the problem is. A few questions off the top of my head:

1. What platform/platforms exhibit this problem?
2. Does this happen for fresh installs, updates, or both?
3. What exact version of ECS are you testing with?
4. Are you waiting for `widevine-ready` before opening the BrowserWindow?

**Comment by andymartinwork** [comment]
1. Windows ia32
2. Both fresh installs and updates
3. I have tested with 15.5.7-wvvmp and 14.2.9-wvvmp
4. Yes, I checked it out and we are waiting.

I did a bit more fine grained testing. It appears that the problem started happening with 14 and continued with 15. When I tried out 16, the problem appears to be resolved. Now I just have to figure out how to release on the windows store...

**Comment by khwaaj** [comment]
Ok, I retested running a clean install of the `v15.5.7-wvvmp` build for `win32-ia32`, executing it on a `win32-x64` host (which is all I currently have immediate access to). This works just fine when testing with the WIP player, including playback and the expected VMP status.

That the same issue exists for you in multiple versions also indicates that the problem you are seeing is unrelated to the original 404-issue, since the fix for that only exists in v15. Best guess is that something in your executing environment is causing issues with the Chromium sandbox. This could very well be related to the Windows Store, as you mention it, since the Desktop Bridge has some weird behavior that conflicts with the Chromium sandbox. Have you tuned the installation of the Widevine CDM somehow to make it work with the Windows Store in the first place?

**Comment by andymartinwork** [comment]
This issue is outside the windows store, I haven't attempted the upgrade there yet.

I wasn't able to figure out what the problem was in the end, but I will just attempt to push past it by moving to 16.

As you said, it's probably not related to this issue as it is present in v14, so I will close the issue.
