### ISSUE TITLE
HTTPError: Response code 404 (Not Found) for https://github.com/castlabs/electron-releases/releases/download/v18.0.1/electron-v18.0.1-win32-x64.zip

### ISSUE THREAD

**Issue by meforce** [castlabs/electron-releases#128]
`npm install "https://github.com/castlabs/electron-releases#v18.0.4+wvcus" --save-dev`

`HTTPError: Response code 404 (Not Found) for https://github.com/castlabs/electron-releases/releases/download/v18.0.4/electron-v18.0.4-win32-x64.zip`

does not define after +

it should be
`https://github.com/castlabs/electron-releases/releases/download/v18.0.4+wvcus/electron-v18.0.4+wvcus-win32-x64.zip`

What's the solution?

**Comment by khwaaj** [comment]
We have seen this with older versions of `npm`, e.g. see #125, so upgrading to a later version should take care of it.

**Comment by meforce** [comment]
thanks. 6 hours wasted :D node js 17 solved everything :D thanks for your help

**Comment by arcovoltaico** [comment]
node -v = v20.14.0
 electron-packager-widevine ./

Response code 404 (Not Found) for https://github.com/castlabs/electron-releases/releases/download/v24.1.2/electron-v24.1.2-darwin-x64.zip

**Comment by khwaaj** [comment]
> node -v = v20.14.0 electron-packager-widevine ./
> 
> Response code 404 (Not Found) for https://github.com/castlabs/electron-releases/releases/download/v24.1.2/electron-v24.1.2-darwin-x64.zip

Do you have the correct version (with `+wvcus`) in your `package.json`? E.g:
```
  "devDependencies": {
    "electron": "github:castlabs/electron-releases#v24.1.2+wvcus",
  },
```

**Comment by arcovoltaico** [comment]
yes, and I did run npm i. when I ran npm start:
node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework' (no such file),
node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGABRT
ERROR: "electron:serve" exited with 1.

**Comment by khwaaj** [comment]
This is [another known issue](https://github.com/castlabs/electron-releases/issues/144), one where symlinks in zip archives are not properly extracted. We have not been able to fix it since the problem seems to be in lower layers of the implementation and is intermittently triggered by certain zip archives.

There is a workaround in that thread, not very nice but it is what we have for now. Using a different version might also work since this problem only exists for some zip archives.
