### ISSUE TITLE
[Help] Unable to "load" CDM in recently Mac OS app

### ISSUE THREAD

**Issue by FatJohn** [castlabs/electron-releases#137]
It seems our electron app on Mac not able to load CDM in recently build. and Our CI build process didn't change.  It worked well l before Nov, 22.
We also follow the guide to use EVS sign in electron forge hook  'packageAfterCopy` which is before code sign by apple.  

And recently the build not able play. Based on player error it's the CDM module not loaded correctly.
I've also use  `verify-package` command to see if is signed by EVS correctly and it shows ok.  

I have found a `workaound` which is delete the certificate needed by code sign in the keychain. And the build would able to use CDM to play.
Its very strange that even I'm not go through code sign but with certificate installed the build would not able to load CDM.
(This workaound is not a valid way. cause we have to distribute our app to customers)

btw, no matter able / not able to paly , I can see  CDM was downloaded by `component api` in directory.

Do you have any idea what's going on ?

**Comment by khwaaj** [comment]
We have not had any reported issues relating to the CDM not loading, and quick test here shows everything working (although without code-signing since I don't have an Apple certificate handily available). I'm not sure which ECS version you are using though, since you didn't specify.

Since Apple code-signing is involved this could have something to do with notarization. Did you disable library validation as [described in the FAQ](https://github.com/castlabs/electron-releases/wiki/FAQ#what-kind-of-notarization-is-necessary-on-macos-catalina-1015-and-later)?

**Comment by FatJohn** [comment]
Hi I've solved this issue.

It turns out that `Electron-Forge` had upgrade its version from 6.0 beta to [6.0 release](https://github.com/electron/forge/releases/tag/v6.0.0). And there's breaking change.

Electron forge changes its osx-codesigned package and we have to modify our forge config to let new osx code-signed packge working correctly. 
```
The upgrade to Electron Packager 17 introduces the shiny new @electron/osx-sign package for macOS code signing. It's a rewrite of the old electron-osx-sign tool with more sensible defaults.

To migrate, we recommend seeing if the default packagerConfig.osxSign options work for you and tweaking the default entitlements to your needs. Otherwise, see the @electron/osx-sign [MIGRATION.md](https://github.com/electron/osx-sign/blob/main/MIGRATION.md) doc for a 1:1 conversion from the old config options to the new ones.
```

Thanks for your reply. :)
