### ISSUE TITLE
"Electron.app" is damaged and can't be opened

### ISSUE THREAD

**Issue by slhck** [castlabs/electron-releases#148]
I downloaded the [electron-v23.1.3+wvcus-darwin-arm64.zip](https://github.com/castlabs/electron-releases/releases/download/v23.1.3%2Bwvcus/electron-v23.1.3+wvcus-darwin-arm64.zip) file.

But for some reason I cannot open the app:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/582444/225598813-0cfe5f95-6ec5-40d7-afe4-7fad36584e6f.png">

This appears whenever I try to start `Electron.app` or run it from within Electron Fiddle.

My system:

<img width="698" alt="image" src="https://user-images.githubusercontent.com/582444/225598928-5427d694-00a9-45bc-a8fc-fc3761628520.png">

**Comment by slhck** [comment]
It appears that running this fixes the problem:

```
sudo xattr -d com.apple.quarantine Electron.app
```

I think it would be good to add this to the documentation somewhere?

**Comment by khwaaj** [comment]
For the record, this is not something we are doing (and the behavior would be the same with stock Electron).

If you download the Electron zip with something like Safari on macOS it will add the quarantine tag to the zip. If you then extract the archive in the Finder it will propagate to `Electron.app` as well, yielding the behavior you are seeing. This is not typically how Electron should be used though, since it is not really a complete application by itself. Using something like `npm`/`yarn` to create a build environment for your own application based on electron will not exhibit this problem.

**Comment by slhck** [comment]
I understand! It's just the error message that's not very informative. In my case I am using Electron Fiddle which does require the custom app file and exhibit the same issue. Maybe future readers will find this issue.
