### ISSUE TITLE
Multiple persistent license requests are going to download an offline widevine license.

### ISSUE THREAD

**Issue by anysongs** [castlabs/electron-releases#149]
# Multiple persistent license requests are going to download an offline widevine license.

### Python : 3.9.0

*exe name : electron.exe
After EVS sign process compete it create electron.exe.sig*

I haven't done any codesign or EVS signing processes for my application yet. We have a thousand files there to download as offline licenses. It takes too much time. Now we are trying to optimise offline license download time. Till now, Shakaplayer has requested two persistent license requests for each offline license download. To reduce the time, we want to make one request for each offline license download. As per my understanding, we need to create a [Verified Media Path (VMP)](https://www.widevine.com/news), after the EVS sign completes, It will reduce the request count to one. For that, I followed the CastLabs electron documentation and tried to do EVS sign to my exe using the ```python3 -m castlabs_evs.vmp sign-pkg --persistent path/to/package-directroy ``` command, and the electron.exe.sig file was successfully generated. Then also shaka making two requests. Is there anything I missed during the EVS signing process? Is there another way to reduce the number of persistent license requests?

![image](https://user-images.githubusercontent.com/28562713/226651108-ab95ad57-f1be-4ead-8840-acab197eb7ac.png)

**Comment by khwaaj** [comment]
The number of requests sent has nothing to do with VMP, however the ability to use persistent licenses at all does. Also, if you are on ECS version 6 you should really consider updating, it is very old and not even officially supported anymore by the Widevine CDM. The official requirement is at least Chromium M95, which means ECS 16 or later (although it may still work with earlier versions, for now).

About your problem, I can't tell for sure by your picture, but my guess is that the first request for each session is a service certificate request. This can be avoided if you provide the cert ahead of time, or load it once and then reuse it. This Shaka Player tutorial has some examples: https://shaka-player-demo.appspot.com/docs/api/tutorial-widevine-service-certs.html

**Comment by khwaaj** [comment]
Are you sure there are not just two sets of keys for Widevine defined in the MPD you are downloading (e.g. for different tracks or qualities)?

**Comment by khwaaj** [comment]
The MPD looks mostly ok, however the DASH-IF implementation guidelines specifies that [`SHALL be present in the AdaptationSet element and apply to all contained Representations`](https://dashif-documents.azurewebsites.net/DASH-IF-IOP/master/DASH-IF-IOP.html#CPS-MPD4CENC-Constraints), so that could be one thing to improve. I doubt it is the culprit here though.

> As I replayed the last thread, I noticed a small difference in the first line between two responses. Is this the problem?

I can't easily tell what this is without request/response headers. The certificate request has just a 2-byte request payload, so that is an easy way to distinguish it. License requests are much larger.

Ultimately this is not an issue with ECS, it is with the player implementation (and/or content DRM integration). You would see the exact same behavior executing the same code in Chrome. ECS provides the interface to the CDM, which is used through EME by the player, nothing else. It could be that Shaka is creating separate EME sessions for A/V (since both are present in the manifest), requesting keys for both sessions even though the keys are really the same. I'm not very familiar with the Shaka implementation though so it is just speculation (although having separate A/V key is standard practice for DRM protected content).

**Comment by anysongs** [comment]
@khwaaj 
Shakaplayer storage.store flow serverCertificate will not be honoured. With some custom changes in Shakeplayer code working now thanks for your support
