### ISSUE TITLE
"Unknown Error" when loading persistent license

### ISSUE THREAD

**Issue by re-jim** [castlabs/electron-releases#17]
Windows 10
Using this release: https://github.com/castlabs/electron-releases.git#v1.8.7-hdcp-vmp1010
Building with [electron-builder](https://github.com/electron-userland/electron-builder)

My app does this:
- Load a widevine-encrypted dash video, with a persistent license.
- Get playback
- Unload the video
- Load the same dash video, reusing the same session
- Get playback.

This works when my app is started with `electron .`, but when I build the app into an executable using electron-builder, it fails at the final step. It can never replay the video using the saved session.

Instead I get this error: `Could not load session (C6898B8297A8EA31040DB3E6E5A74E4C)! UnknownError`

after doing: `mediaKeys.createSession(sessionType).load(sessionId)`

**Comment by khwaaj** [comment]
This is likely because to electron-builder is invalidating the provided VMP signature by making changes to the executable (adding an icon, etc). You'll need to get your own VMP signing certificates and re-sign the application after packaging (or get electron-builder to leave electron.exe as-is) . Take a look at [the VMP section](
https://github.com/castlabs/electron-releases/tree/v1.8.7-hdcp-vmp1010#verified-media-path-vmp) of the [README](
https://github.com/castlabs/electron-releases/tree/v1.8.7-hdcp-vmp1010#castlabs-electron-release-for-content-security).

**Comment by re-jim** [comment]
Thanks for the speedy response
