### ISSUE TITLE
Widevine CDM Library removal issue

### ISSUE THREAD

**Issue by charlesstrube** [castlabs/electron-releases#173]
# Issue Description:
We are encountering a persistent issue with the Widevine CDM library in castLabs Electron releases. Initially, we were using version 16 and observed that the Widevine CDM library was being removed unexpectedly on macos and windows. Following the advice on [your status page](https://github.com/castlabs/electron-releases/wiki#status), which indicates potential issues with versions below 21, we upgraded to version 25. Unfortunately, the problem persists even after the upgrade.

# Steps to Reproduce:
1. Start with castLabs Electron version 16, where Widevine CDM is expected to function.
2. Remove content of the CDM folder `~/Library/Application Support/%appname%/WidevineCdm` (macOS)
3. Protected content doesn't play anymore
4. Upgrade to version 25, anticipating resolution of the issue based on the [official status page](https://github.com/castlabs/electron-releases/wiki#status) guidelines.
5. Find that the issue persists with version 25, where the `~/Library/Application Support/%appname%/WidevineCdm` folder  remains empty.

# Expected Behavior:
We expect that upgrading to a version within the supported range (version 25) would resolve the issue, redownloading the Widevine CDM library.

# Actual Behavior:
Despite upgrading to version 25, the Widevine CDM library continues to be removed for some users, with no success in redownloading or restoring the DRM files.

# Additional Information:
This issue does not affect all users, but it is significant for those it does and it increases each day.

# Questions and Assistance Required:
- Are there any known issues regarding Widevine CDM that might explain this behavior?
- Could you provide guidance or a workaround for manually reinstalling or restoring the Widevine CDM library in these cases?

**Comment by khwaaj** [comment]
Thank you for your report. There are no currently known issues that could explain this behavior, and a few initial tests on our side can't reproduce what you are describing using the latest build of ECS v25.

After Google started more strictly observing this policy, we made some improvements to the Components API to try and catch some of these problems and report them as errors to the application. These changes are available in the most recent builds of ECS v28-v25, but I don't know exactly which version you are on so I can't say for sure if you have the updates or not.

When these updates are available a failed installation would result in a promise rejection from `components.whenReady()`, which could at least help detect when these errors happen instead of just silently failing. We also provide more detailed error information in the [promise rejection `Error`](https://github.com/castlabs/electron-releases/blob/master/docs/api/components.md#componentswhenreadyrequired), which can hopefully help to figure out what is going on.

Are you able to reproduce this issue yourselves? If so, there is also some logging that can be enable which could provide hints as to what is going on. Here is an example command line I have been using to test this issue locally:
```console
$ Electron.app/Contents/MacOS/Electron --enable-logging "--vmodule=*install*=3,*crx*=3,*update*=3,*widevine*=3,*cdm*=3,*request_sender*=3" wip-uat-player.js
```

`wip-uat-player.js` is simply a small script that executes `await components.whenReady()` prior to opening a window with the [WIP UAT player](https://integration.uat.widevine.com/player).

**Comment by charlesstrube** [comment]
I tried to put a catch, but we don't fall in it

### Additional Information
**Blocked Requests**: It appears Google is blocking our requests when we attempt to access the CDM.
**Inconsistent Update Responses**: The response indicates the availability of an update, but this varies across different computers.
**API Call Analysis**: Utilizing Charles to monitor the API call to https://update.googleapis.com/service/update2/json, we have observed two distinct types of responses.
### Observed Responses
Here are the examples of the responses we've captured:

- user with noupdate body set in post: 
```{
	"request": {
		"@os": "mac",
		"@updater": "chromium",
		"acceptformat": "crx2,crx3",
		"app": [{
			"appid": "oimompecagnajdejgnnjijobebaeigek",
			"cohort": "1::",
			"cohortname": "Chrome 106+",
			"enabled": true,
			"installsource": "ondemand",
			"ping": {
				"ping_freshness": "{uuid}",
				"rd": 6170
			},
			"updatecheck": {},
			"version": "0.0.0.0"
		}],
		"arch": "arm64",
		"dedup": "cr",
		"domainjoined": true,
		"hw": {
			"physmemory": 16
		},
		"ismachine": false,
		"lang": "en-GB",
		"nacl_arch": "arm64",
		"os": {
			"arch": "arm64",
			"platform": "Mac OS X",
			"version": "14.1.0"
		},
		"prodversion": "96.0.4664.45",
		"protocol": "3.1",
		"requestid": "{uuid}",
		"sessionid": "{uuid}",
		"updaterversion": "96.0.4664.45"
	}
}
```
and the response here 
```
)]}'
{
	"response": {
		"server":"prod",
		"protocol":"3.1",
		"daystart":{
			"elapsed_seconds":20690,
			"elapsed_days":6171
		},
		"app":[
			{
				"appid":"oimompecagnajdejgnnjijobebaeigek",
				"cohort":"1::",
				"status":"ok",
				"cohortname":"",
				"ping":{"status":"ok"},
				"updatecheck":{"status":"noupdate"}
			}
		]
	}
}
```

- user that gets the update
```
{
	"request": {
		"@os": "mac",
		"@updater": "chromium",
		"acceptformat": "crx3",
		"app": [{
			"appid": "oimompecagnajdejgnnjijobebaeigek",
			"enabled": true,
			"installsource": "ondemand",
			"lang": "fr",
			"ping": {
				"r": -2
			},
			"updatecheck": {},
			"version": "0.0.0.0"
		}],
		"arch": "arm64",
		"dedup": "cr",
		"domainjoined": true,
		"hw": {
			"avx": false,
			"physmemory": 16,
			"sse": false,
			"sse2": false,
			"sse3": false,
			"sse41": false,
			"sse42": false,
			"ssse3": false
		},
		"ismachine": false,
		"nacl_arch": "arm",
		"os": {
			"arch": "arm64",
			"platform": "Mac OS X",
			"version": "14.1.1"
		},
		"prodversion": "114.0.5735.289",
		"protocol": "3.1",
		"requestid": "{uuid}",
		"sessionid": "{uuid}",
		"updaterversion": "114.0.5735.289"
	}
}
```

Notably, in the 'no update' response, we have the "cohort": "1::" field set. But it might not be related
If you know how we can force the update, that would be awesome

**Comment by khwaaj** [comment]
Ok, that does actually explain it. The request that is not getting an update has `"prodversion": "96.0.4664.45"`. That corresponds to ECS v16, which is way outside of the window of supported versions.

Any idea why that would be?

**Comment by charlesstrube** [comment]
Just a quick update: we've identified an error on our end. One of our recent builds mistakenly didn't include the latest version of Electron, which explains the observed differences in behavior. It does fix the issue for the impacted users. Thanks to @khwaaj — your comments helped us solve this problem.
