### ISSUE TITLE
arm support for Windows using ia32 binaries broken since Electron 25

### ISSUE THREAD

**Issue by andymartinwork** [castlabs/electron-releases#175]
We use 32bit Electron builds of our app for compatibility with running on arm based versions of windows. It's possible to test this if you have no arm based windows machine by running windows on mac through parallels.

I updated Electron to the latest castlabs version (28) and encountered this exception in `components.whenReady`:

```
{
  "errors": [
    {
      "detail": {
        "id": "neifaoindggfcjicffkgpmnlppeffabd",
        "status": "not-installed",
        "title": "Google Widevine Windows CDM",
        "version": null
      }
    }
  ]
}
```

I tracked the break to castlabs electron 24 -> 25

The downloaded version of the Widevine CDM is `4.10.2710.0`, both for 24 and 25.
I'm wondering if there's something that changed in the castlabs implementation between these versions and if there's anything I can do about it?

Electron 24 to 25 jumps from Chromium 112 to 114 if that helps.

**Comment by khwaaj** [comment]
Ok, this is not the regular Widevine CDM, but the L1 CDM that is available on Windows only. Apparently it is not available in this case though, it might not be available on 32-bit Windows at all, but I need to check that.

Since we hardened the installation checks as a consequence of the recent CDM removals for older versions of Chromium by Google, we explicitly check that the installation of required components was successful. This is why you are seeing the error here, because by default we require both CDMs on Windows.

Fortunately there is a way around this already, while we investigate whether this should be the default for Windows or not (especially 32-bit). The [components.whenReady()](https://github.com/castlabs/electron-releases/blob/master/docs/api/components.md#componentswhenreadyrequired) function now takes an optional argument that can be used to specify which components are considered required.  So if all you need is the standard Widevine L3 CDM, you can pass that to the `whenReady()` call, e.g:
```js
app.whenReady().then(async () => {
  try {
    let result = await components.whenReady([components.WIDEVINE_CDM_ID]);
    console.log('1: components result:', result);
    let status = components.status();
    console.log('1: components status:', status);
    createWindow();
  } catch (e) {
    console.log('caught error:', e);
    if ('errors' in e) {
      for (error of e.errors) {
        console.log('error:', error);
      }
    }
    app.exit(1);
  }
});
```

**Comment by andymartinwork** [comment]
This seems to fix my problem, and the CDM still works on Windows arm64. Thank you!
