### ISSUE TITLE
A beta version of electron was chosen for the castlabs release version

### ISSUE THREAD

**Issue by andymartinwork** [castlabs/electron-releases#2]
I guess the castlabs release of this software is therefore in beta and shouldn't be used in production?

Probably something that should be highlighted in your documentation.

**Comment by khwaaj** [comment]
This is indeed based on a beta Electron release, and we should probably clarify that. The reason for using 1.8.x is that VMP is not available in Chromium versions prior to 59, which is introduced in the 1.8-series. We’ll update with a 1.8.x non-beta as soon as the Electron team makes a stable release.

That said we actually have the ability to make a VMP-enabled 1.7.x-based release. It requires significantly more maintenance than 1.8.x though, which is why we have not published such a release here at this point. If there is demand for it we are likely to reconsider,.

**Comment by andymartinwork** [comment]
No need for 1.7.x on this end, I'm sure 1.8 will be out of beta soon enough.

**Comment by khwaaj** [comment]
Modified release to clearly show its pre-release state.
