### ISSUE TITLE
Widevine signing issue with electron build

### ISSUE THREAD

**Issue by triola** [castlabs/electron-releases#22]
After creating an electron build using 'nmp run release' and then VMP signing that .exe following the instructions here: https://github.com/castlabs/electron-releases#verified-media-path-vmp I can open the .exe but the videos fail to play. With the console open we can what look to be various code signing issues.

At this point we just don't know enough about the system to begin debugging. Is there any way to tell that the VMP signing was successful? Is there a way that we can troubleshoot our widevine certificate?

To be clear, our use case is that a user will download content with an internet connection, and then later play that content without an internet connection.
![unnamed](https://user-images.githubusercontent.com/1554535/45777792-6ab2a980-bc1c-11e8-80d1-c4b73b7da643.png)

Thanks,
Ben

**Comment by khwaaj** [comment]
Hi Ben,

There are any number of reasons a license request can fail so I would need some more details to be able to help you. First off, I can see that you are on Win32/x64 from the picture, but which Electron release are you using? I'm asking because there was an issue with 3.0.0-beta.10 that affected Win32/x64 and possibly could be the culprit here.

The 403 Forbidden result could indicate that there is a VMP signature issue though. Can you post the entire response, including the HTTP headers? There should be some information there that can help in determining if this is a VMP signing failure.

**Comment by triola** [comment]
running process.version.electron from the consol of the app returns `1.8.7`

after the video failed to play I looked at the network tab in developer tools. Below are the headers / response for the failed request. I'm curious, if the app is offline and unable to make the request to the drm server, what is supposed to happen at that point?

```
Request URL:https://lic.drmtoday.com/license-proxy-widevine/cenc/
Request Method:POST
Status Code:500 Creating forward request failed
Remote Address:52.52.248.209:443
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:x-dt-custom-data,dt-custom-data,http-header-CustomData,x-dt-auth-token,x-dt-client-info,x-dt-follow-up-token,x-dt-csl-renewal-info,x-dt-csl-tracking-token,origin,content-type,accept,x-requested-with
Access-Control-Allow-Methods:POST,PUT,DELETE,GET,OPTIONS,HEAD,TRACE,PATCH
Access-Control-Allow-Origin:file://
Access-Control-Expose-Headers:x-dt-custom-data,dt-custom-data,http-header-CustomData,x-dt-auth-token,x-dt-client-info,x-dt-follow-up-token,x-dt-csl-renewal-info,x-dt-csl-tracking-token,origin,content-type,accept,x-requested-with
Connection:keep-alive
Content-Language:en
Content-Length:820
Content-Type:text/html;charset=utf-8
Date:Wed, 19 Sep 2018 20:47:07 GMT
Server:DRMtoday
Strict-Transport-Security:max-age=31536000;includeSubDomains
Vary:Accept-Encoding,Origin
X-Content-Type-Options:nosniff
x-dt-client-info:eyJtYW51ZmFjdHVyZXIiOiJHb29nbGUiLCJtb2RlbCI6IkNocm9tZUNETS1XaW5kb3dzIiwiZHJtVmVyc2lvbiI6IjAiLCJzZWNMZXZlbCI6MywiaGRjcFN1cHBvcnQiOiJIRENQX05PTkUiLCJ2ckNvbnN0cmFpbnRTdXBwb3J0IjpmYWxzZSwidm1wU3RhdHVzIjoiUExBVEZPUk1fVEFNUEVSRUQifQ==
X-Frame-Options:DENY
X-XSS-Protection:1; mode=block
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:en-US
Connection:keep-alive
Content-Length:5171
dt-custom-data:eyJ1c2VySWQiOiJwdXJjaGFzZSIsInNlc3Npb25JZCI6InAwIiwibWVyY2hhbnQiOiJzcG90bXBnIn0=
Host:lic.drmtoday.com
Origin:file://
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) PrestoPlayDesktopBasic/1.0.1 Chrome/59.0.3071.115 Electron/1.8.7 Safari/537.36
X-DevTools-Request-Id:10384.51
```

**Comment by khwaaj** [comment]
Ok, 1.8.7 should work fine but make sure you are using 1.8.7-hdcp (or 1.8.8) though or you may run into a HDCP related issue that was present on Windows for the initial 1.8.7 release. That is not the current issue you are seeing though, just a side note.

I can see from the requests that you are getting a PLATFORM_TAMPERED status from the VMP verification, so there is something wrong with the signature in this case. There are a few things that can cause this. The one I've found most common is that the executable is changed after the VMP signing has taken place, thus invalidating the signature. This can happen as part of a packaging or code-signing process if it happens after the VMP signing. The thing to check first though is that there is a corresponding .sig-file next to your application executable, e.g. MyApp.exe should have a corresponding MyApp.exe.sig in the same folder.

Assuming the .sig-file exists in its proper place the next step would be to verify that the signature is correct. There is a python tool that is usually provided by the Widevine team during the licensing process that is capable of doing this (signature_checker.py, I believe), so if you have access to that you could try to verify the signature using it. If not, the vmp-resign.py script already contains most of the necessary functionality and I've been meaning to add verification to it so maybe it is time I do that.

To answer your final question, if the app is offline any network license request will fail. To avoid that you need to request a persistent license and load the persisted session instead of making a network request for your offline content. Exactly how this works at the JavaScript level is a bit outside my area of expertise, but if you are using something like [DOWNstream for Electron](https://github.com/castlabs/downstream_electron/) that is probably a good place to start looking.

**Comment by khwaaj** [comment]
I just added a `-Y` option to the `vmp-resign.py` script that allows verifying the VMP signature. You'll need to download the [script from the master branch](https://github.com/castlabs/electron-releases/blob/master/vmp-resign.py) and use that instead of the script included in the release. For more verbose logging add one or more `-v` switches as well.

**Comment by triola** [comment]
Thanks for adding that. Does vmp-resign require Python 3? I get this error when I try to sign: `AttributeError: 'int' object has no attribute 'to_bytes'`

**Comment by khwaaj** [comment]
Yes, it uses some features not available until Python 3.

**Comment by triola** [comment]
Ok, I've VMP signed the electron.exe. I can see electron.exe.sig.

Then I run `python3 vmp-resign.py -Y  electron-win32-x64/` and I get
`vmp-resign/ERROR: Package verificaton failed: electron-win32-x64/`

verbose output looks like this:
`vmp-resign/INFO: Verifying package: electron-win32-x64/
vmp-resign/INFO: Reading signature from: electron-win32-x64/electron.exe.sig
vmp-resign/INFO: Verifying file: electron-win32-x64/electron.exe
vmp-resign/INFO: Verifying signature for: electron-win32-x64/electron.exe
vmp-resign/ERROR: Package verificaton failed: electron-win32-x64/`

**Comment by triola** [comment]
sudo python3 vmp-resign.py -C spot_vmp_certs/spot-prod-cer.der -K CSR_key_generation/production-key.pem -P "mypassword" electron-win32-x64/

```
vmp-resign/INFO: Loading DER certificate: spot_vmp_certs/spot-prod-cer.der
vmp-resign/INFO: Loading PEM key: CSR_key_generation/production-key.pem
vmp-resign/INFO: Resigning package: electron-win32-x64/
vmp-resign/INFO: Signing file: electron-win32-x64/electron.exe
vmp-resign/DEBUG: File digest: e6c41a5b4835e471b3c542ef16e378f0e493f6de0b4cef9d172ac9b5e266ac0e4d30f665b1fd96370b39b0bf5b8b0ba06d5a5222ed2847f312fa99bf5ba550b5
vmp-resign/DEBUG: Signing data: e6c41a5b4835e471b3c542ef16e378f0e493f6de0b4cef9d172ac9b5e266ac0e4d30f665b1fd96370b39b0bf5b8b0ba06d5a5222ed2847f312fa99bf5ba550b501
vmp-resign/DEBUG: Encoding signature data
vmp-resign/INFO: Writing signature to: electron-win32-x64/electron.exe.sig

```


-------------------------------------------------------------------------------------


python3 vmp-resign.py -Y  -vv electron-win32-x64/

```
vmp-resign/INFO: Verifying package: electron-win32-x64/
vmp-resign/INFO: Reading signature from: electron-win32-x64/electron.exe.sig
vmp-resign/DEBUG: Decoding signature file with version: 0
vmp-resign/DEBUG: Decoding certificate entry
vmp-resign/DEBUG: Decoding signature entry
vmp-resign/DEBUG: Decoding flags entry
vmp-resign/INFO: Verifying file: electron-win32-x64/electron.exe
vmp-resign/DEBUG: File digest: e6c41a5b4835e471b3c542ef16e378f0e493f6de0b4cef9d172ac9b5e266ac0e4d30f665b1fd96370b39b0bf5b8b0ba06d5a5222ed2847f312fa99bf5ba550b5
vmp-resign/DEBUG: Verifying data: e6c41a5b4835e471b3c542ef16e378f0e493f6de0b4cef9d172ac9b5e266ac0e4d30f665b1fd96370b39b0bf5b8b0ba06d5a5222ed2847f312fa99bf5ba550b501
vmp-resign/ERROR: Package verificaton failed: electron-win32-x64/
```

**Comment by khwaaj** [comment]
Interesting, the digests do match. The only thing I can think of that would yield a result such as this would be if the private key used does not match the certificate. I'll see about adding a check for that in the script so that we can verify that is the case.

**Comment by khwaaj** [comment]
Just pushed an update of vmp-resign-py to master that includes validation of the certificate and key. If you re-run the signing using this we should be able to tell if there is a mismatch between the two.

If this happens to be the case, could there simply have been a mix up so that the dev/prod certs and keys have been exchanged at some point?

**Comment by triola** [comment]
Ok, thanks for getting back to me so fast. I'll give that a try. We're also having some new certs issued in case there's some inherent problem with these.

**Comment by triola** [comment]
Looks like we have our answer. I'm not sure why they wouldn't match, but hopefully the new keys will fix the issue.

```
vmp-resign/INFO: Loading DER certificate: spot_vmp_certs/spot-prod-cer.der
vmp-resign/INFO: Loading PEM key: CSR_key_generation/production-key.pem
vmp-resign/ERROR: Private key does not match the certificate public key
Traceback (most recent call last):
  File "vmp-resign.py", line 399, in <module>
    main()
  File "vmp-resign.py", line 384, in main
    validate_cert_and_key(cert, key)
  File "vmp-resign.py", line 283, in validate_cert_and_key
    raise ValueError('Private key does not match the certificate public key')
ValueError: Private key does not match the certificate public key
```

**Comment by triola** [comment]
Just got the new certs. This looks better?

sudo python3 vmp-resign.py -vv -C spot_vmp_certs_round_2/spot2-prod-cer.der -K CSR_round_2/production-key.pem -P "password" electron-win32-x64/


```
vmp-resign/INFO: Loading DER certificate: spot_vmp_certs_round_2/spot2-prod-cer.der
vmp-resign/INFO: Loading PEM key: CSR_round_2/production-key.pem
vmp-resign/DEBUG: RSA key size: 2048
vmp-resign/INFO: Resigning package: electron-win32-x64/
vmp-resign/INFO: Signing file: electron-win32-x64/electron.exe
vmp-resign/DEBUG: File digest: e6c41a5b4835e471b3c542ef16e378f0e493f6de0b4cef9d172ac9b5e266ac0e4d30f665b1fd96370b39b0bf5b8b0ba06d5a5222ed2847f312fa99bf5ba550b5
vmp-resign/DEBUG: Signing data: e6c41a5b4835e471b3c542ef16e378f0e493f6de0b4cef9d172ac9b5e266ac0e4d30f665b1fd96370b39b0bf5b8b0ba06d5a5222ed2847f312fa99bf5ba550b501
vmp-resign/DEBUG: Encoding signature data
vmp-resign/INFO: Writing signature to: electron-win32-x64/electron.exe.sig
```


python3 vmp-resign.py -Y  -vv electron-win32-x64/

```
vmp-resign/INFO: Verifying package: electron-win32-x64/
vmp-resign/INFO: Reading signature from: electron-win32-x64/electron.exe.sig
vmp-resign/DEBUG: Decoding signature file with version: 0
vmp-resign/DEBUG: Decoding certificate entry
vmp-resign/DEBUG: Decoding signature entry
vmp-resign/DEBUG: Decoding flags entry
vmp-resign/INFO: Verifying file: electron-win32-x64/electron.exe
vmp-resign/DEBUG: File digest: e6c41a5b4835e471b3c542ef16e378f0e493f6de0b4cef9d172ac9b5e266ac0e4d30f665b1fd96370b39b0bf5b8b0ba06d5a5222ed2847f312fa99bf5ba550b5
vmp-resign/DEBUG: Verifying data: e6c41a5b4835e471b3c542ef16e378f0e493f6de0b4cef9d172ac9b5e266ac0e4d30f665b1fd96370b39b0bf5b8b0ba06d5a5222ed2847f312fa99bf5ba550b501
vmp-resign/INFO: Package verification succeeded: electron-win32-x64/



```

**Comment by khwaaj** [comment]
Much better! Take it for a spin and see if the re-signed Electron it works better too, hopefully it should.

**Comment by triola** [comment]
That seems to work.

Alec had showed us how to use npm run eb to make a standalone .exe.  Is there any way to sign the standalone app? That would be the easiest way for our clients to use the app, but of course won't work unless signed.

**Comment by khwaaj** [comment]
Nice!

Exactly, you'll need to sign the app after packaging (or at the end of packaging if there is some way to hook into the actual process, but I'm not familiar with that). This can be done with the vmp-resign.py script much like you have done now, but you'll need to use the `-M` and/or `-W` switches to provide the correct name.

**Comment by triola** [comment]
Hey Emil, something weird is happening.

This was working this morning, and now, without changing anything, it's no longer working (videos don't play). I did a new build with the dev panel open, signed it, did the VMP verification and everything checks out. But when I go to play the video I'm getting some errors I haven't seen before. They look like 500 internal server errors from drmtoday.com

![unnamed-2](https://user-images.githubusercontent.com/1554535/45909403-3fb88900-bdc7-11e8-9cb1-3652f76300bf.png)

Let me know if you have any thoughts. The client's deadline is quickly approaching, so if we can get something figured out I'll come back in over the weekend to rebuild.

Thanks!

**Comment by khwaaj** [comment]
Closing since the issue at hand has been resolved.
