### ISSUE TITLE
Clarifying behaviour when widevine-ready fires after upgrade to v3

### ISSUE THREAD

**Issue by simongregory** [castlabs/electron-releases#28]
I'm working on our next release which sees us moving up to Electron v3. Reading your docs on [`widevine-ready`](https://github.com/castlabs/electron-releases#widevine-ready) I understood the event fires once it's possible to use the CDM. However it always fires during upgrade scenarios where the older, existing 1.4.8 version of the CDM is loaded into v3, this isn't something I'd anticipated. As all our licences are persistent this leaves us with content that doesn't play ([as expected](https://github.com/castlabs/electron-releases#migrating-from-an-earlier-castlabs-electron-for-content-security-release)).

The [`widevine-update-pending`](https://github.com/castlabs/electron-releases#widevine-update-pending) then fires shortly after and on restarting the app and re-fetching the licences all is well again.

As this leaves users without the ability to play content in the interim period I've got a few questions:

 * If licenses are re-fetched with v3 and 1.4.8 will they work, are they restricted ie online only?
 * I'm expecting `widevine-update-pending` to fire at any point the app is running, are the actual cases more restricted than that?
 * Are clients expected to maintain a compatible list of CDM versions based on the features they want then fail to holding/error states until a suitable `widevine-update-pending` event fires? If so what are the rules?

**Comment by simongregory** [comment]
I've attempted to answer the first question and can see that licences are issued using v3 and 1.4.8, they just don't work for us. This is for both temporary and persistent sessions  - what I can't remember is if I should expect the key session id to belong to the browser, or browser window. If it's the latter it wouldn't work for us anyway.

**Comment by khwaaj** [comment]
Interesting, this is actually something that I explicitly tested when I initially did the v3 implementation, and at that point using the 1.4.8 CDM, installed by a previous version, worked fine (the chromium backend still supports the older CDM API). We want to use 1.4.9 for v3 though since 1.4.8 doesn't support StorageID, so it will be upgraded at the first possible opportunity.

Obviously I'll need to re-test this to make sure there isn't some kind of regression at work here. For the record, what exact version(s) and system(s) have you tested?

To answer your questions:
* Yes, persistent licenses should work like before, provided the Widevine Proxy config is the same. In fact, even previously stored 1.4.8 offline licenses should work fine, until the update to 1.4.9 is completed (which will invalidate them).
* Yes, currently an update check is only triggered at launch, so you should only be seeing this fairly soon after your app has started.
* Well, maybe under some specific circumstances (like requiring the use of StorageID for some reason), but generally this should not be necessary. It is expected that the client handles migration of the offline licenses when upgrading between CDM API versions though (like 8 to 9 in this case and 9 to 10 in v4). The Widevine team is working on something that should allow automatic migration of persisted licenses between CMD API versions/key-systems at some point, but it is still something that is in the future.

**Comment by khwaaj** [comment]
After some testing I can conclude that temporary/online licenses appear to work with 1.4.8 for all v3 releases on macOS (I have not tested Windows/Linux yet), so I'm not sure why this would not work in your case.

Persistent/offline licenses is another story. This apparently regressed already back in `v3.0.0-wvvmp-beta.12` which makes `beta.10` the only v3-release where this actually worked (this applies to both previously persisted licenses and attempting to get new ones). I'm not sure of the reason as of yet, but I will investigate further. Depending on what I find we may fix the behaviour or simply enforce an immediate upgrade to 1.4.9 when using v3.

**Comment by khwaaj** [comment]
As a temporary workaround your code should work fine, it would wait indefinitely for `widevine-update-pending` in certain scenarios though (like if there is no network access), unless there is some timeout in place that I can't see above. For v3 your check for 1.4.9.x should be safe though.

No, StorageID is a feature of the CDM that protects the persisted sessions. It was not available before CDM API version 9 though, so for earlier CDM versions there had to be other protections in place for the persisted data.

**Comment by khwaaj** [comment]
I just released [electron 3.0.11-wvvmp.1](https://github.com/castlabs/electron-releases/releases/tag/v3.0.11-wvvmp.1), which makes sure to always update to 1.4.9 during first launch. The whole point of having 1.4.8 support in the first place was to support migration between the two, which we were initially under the impression was possible, but now that it has been established not to be, doing the upgrade immediately will only create a clearer migration path (i.e. always re-requesting the persisted sessions when the `widevine-ready` signals an update from 1.4.8 to 1.4.9).

Let me know how it goes!

**Comment by simongregory** [comment]
Thanks Emil. I've returned our logic back to it's original state - renewing the licences when you report a cdm upgrade. My initial tests were good so I've built and shipped to QA.
