### ISSUE TITLE
Unable to create the CDM for the key system com.widevine.alpha

### ISSUE THREAD

**Issue by andymartinwork** [castlabs/electron-releases#3]
I've been trying to activate our widevine implementation based on shaka player, but I've been getting this error from the browser:

Unable to create the CDM for the key system com.widevine.alpha

I haven't got a publicly accessible version of the problem, but this site displays the same issue:

https://bitmovin.com/mpeg-dash-hls-drm-test-player/

It works fine on Chrome, but since the error message is coming from the browser, there's not much I can do to debug it.

**Comment by khwaaj** [comment]
I'm not sure exactly what you are actually trying to do here, but if you are trying to run a completely web-based player (like the Bitmovin example) within Electron, it is not certain it will run as expected without modification.  Certain javascript packages may be initialized differently due to the fact that Electrons has a combined nodejs and a pure browser environment, which may be the cause of unexpected issues in some cases.

Btw, if you print navigator.plugins in the javascript console, can you see that the "Widevine Content Decryption Module" is listed there?

**Comment by andymartinwork** [comment]
Yes, I see the plugin there when I list the plugins.

Check out this page, which uses native EME - (scroll down to the bottom of the list to the Verizon Digital Media Services options).

https://shaka-player-demo.appspot.com

Is it possible, perhaps, to provide an example app where the DRM in shaka-player-demo site works? Perhaps using the electron-quick-start app as a base?

At the moment, I git clone electron-quick-start and replace the mainWindow.load command to this to test out your build:

`mainWindow.loadURL("http://shaka-player-demo.appspot.com/")`

Perhaps some more setup is necessary?

**Comment by khwaaj** [comment]
Actually I just realized this might be because plugins are disabled in the default BrowserWindow instance. If you enabled them, like in the attached script, the Bitmovin player works fine.

[index.js.zip](https://github.com/castlabs/electron-releases/files/1514274/index.js.zip)

**Comment by andymartinwork** [comment]
Ahh, you're correct - the plugins needed to be enabled. It's working nicely now. Perhaps something for the Readme :-P

**Comment by khwaaj** [comment]
Yeah that is probably a good idea :-)
