### ISSUE TITLE
Help understanding migration docs

### ISSUE THREAD

**Issue by lucasyvas** [castlabs/electron-releases#36]
I'm having trouble understanding what is meant to be done to mitigate the issues that can be caused by migration:

> Due to a changes in the key system id used between major and/or certain vulnerable versions of the Widevine CDM previously persisted licenses cannot be automatically migrated when such a CDM upgrade occurs. **The recommended workaround is to listen for the widevine-ready event and then trigger a manual re-fetch of all persisted licenses in case an update was applied, i.e. if lastVersion is not null and not equal to version (or at least verify the loadability of previously persisted licenses)**. Also, the first request for a new license, temporary or persistent, after such an upgrade will fail with the CDM error Rejected with system code (75) (the same error as when trying to load a session persisted with the previous CDM). This happens because the CDM needs to update the storage to match the new system id. **The suggested solution is to simply retry the request in such cases,** as all subsequent requests should work as usual.

How can I achieve the bolded? Does relaunching the app in the `widevine-ready` event trigger a manual re-fetch or is there another method?

**Comment by khwaaj** [comment]
First, this is a fairly rare occurrence and applies only to persisted/offline licenses, but once it happens simply relaunching the app won't do anything to revive the expired persistent sessions.

As you probably know you work with these in a browser context using the [EME](https://www.w3.org/TR/encrypted-media/) APIs. The electron package only provides the ability to access the Widevine CDM, not the actual EME implementation required to use it. What you would need to do is make sure your EME implementation keeps track of persistent sessions in a way that makes it possible to refresh them. If you have an offline playback solution already you are probably doing this as part of that since you need to keep track of the sessions connected to each offline asset. In essence, once you detect a CDM change that might break the persistent sessions you should try to load one. If they no longer appear to load correctly you should loop through your offline assets and request new persistent sessions for each one in turn. This obviously requires that you are not offline, but if an update of the CDM was applied you should not be anyway.

I hope this makes things a bit clearer!

**Comment by lucasyvas** [comment]
Thanks so much for your reply! It did clear things up :)
