### ISSUE TITLE
Incorrect version for node type definitions

### ISSUE THREAD

**Issue by eugirdor** [castlabs/electron-releases#40]
I believe this is the same issue as #16, but now this project's node type definitions are pinned to 8 and Electron has been on Node.js 10+ since v3.

https://github.com/castlabs/electron-releases/blob/3ebdd617b2580e48bd80664e3eaa9760866c9b17/package.json#L14

https://electronjs.org/releases/stable?version=3&page=6#3.0.0

```
error TS4090: Conflicting definitions for 'node' found at '.../node_modules/@types/node/index.d.ts' and '.../node_modules/electron/node_modules/@types/node/ts3.2/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.
```

It might be easier to use `"@types/node": "*"` so that it uses the same version as the application instead of bringing in its own potentially conflicting version.

**Comment by khwaaj** [comment]
Thanks for the heads-up, this was never properly scripted for our releases and apparently stopped functioning sometime soon after #16 was resolved. I've implemented a much more robust solution in the build scripts now that uses the same basic `package.json` as the original Electron release, so that should hopefully take care of this from now on.

I've just published 4.2.7 which uses the updated scripts and updates for more releases are in the pipeline. Let me know if you have any further trouble!

**Comment by khwaaj** [comment]
Actually I just noticed Electron has some issues with keeping this up to date as well, see [PR #19102](https://github.com/electron/electron/pull/19102). This means the 6.0.0 betas still have node 10 specified when it should be 12, but as soon as the PR is backported to the 6-0-x branch this should correct itself in the following releases.

**Comment by khwaaj** [comment]
Since there have been no further comments and this is essentially a resolved issue, I'll close this for now. Please reopen if you feel differently.
