### ISSUE TITLE
Build package for arm architecture fails

### ISSUE THREAD

**Issue by ivanov35** [castlabs/electron-releases#41]
When I try to build my electron castLabs app for **arm** architecture, it fails with the folowing error:

> cannot resolve https://github.com/electron/electron/releases/download/v7.0.0-wvvmp-beta.3/electron-v7.0.0-wvvmp-beta.3-linux-armv7l.zip: status code 404

I do not have the same problem with architecture amd64.

**Comment by simongregory** [comment]
I don't see an arm build available - https://github.com/castlabs/electron-releases/releases/tag/v7.0.0-wvvmp-beta.3

On top of that is looks like you've not got the correct mirror options setup - so the build tools don't fetch the binary from the correct endpoint. I'd expect a url starting: https://github.com/castlabs/ this might mean your amd64 build isn't Widevine capable.

**Comment by ivanov35** [comment]
In my dependencies, the "electron" option is correctly set to be:

  "electron": "https://github.com/castlabs/electron-releases#v7.0.0-wvvmp-beta.3"

but when building a desktop for arm it comes exactly the error I sent. 

For amd64 I have not a problem to build desktop and to play netflix and amazon after that.

**Comment by simongregory** [comment]
The amd64 build sounds fine, I expect the binary is getting downloaded when you npm/yarn install. A build/package is likely finding it in a local cache because of this. If it wasn't in the cache then I'd expect you to see the same 404.

Configuration for this is a case of following the documentation for your build tools. But ultimately the arm build is going to fail because the binaries aren't available. One of the Castlabs guys are probably best to explain their choice of supported platforms/architectures.

**Comment by khwaaj** [comment]
We are not supporting arm at this time due to missing official CDM support from Google Widevine, see #23 for more details.
