### ISSUE TITLE
Electron 7-0-0 zip unavailable

### ISSUE THREAD

**Issue by Tal-telecomsante** [castlabs/electron-releases#43]
Hi sir !

I got a 404 error when i try to get the following electron zip : https://codeload.github.com/castlabs/electron-releases/zip/7-0-x

All is fine for 6-0-x.

Cause of that i can't build my package with electron-builder.

Thank you in advance and thank you for your work :)

**Comment by khwaaj** [comment]
Hi,

This happens because v7 of electron-releases is in beta and has not yet been branched from master to 7-0-x. Not sure why electron-builder would look at a non-existent branch though, it should be using the direct links for each release version instead, e.g: https://github.com/castlabs/electron-releases/archive/v7.0.0-wvvmp-beta.7.zip

How does your package.json look?

**Comment by khwaaj** [comment]
I think your problem may be with your electron builder configuration. Try something like this instead:

```
"build": {
  "electronDownload": {
    "mirror": "https://github.com/castlabs/electron-releases/releases/download/v"
  }
}
```

and:
```
"devDependencies": {
  "electron": "https://github.com/castlabs/electron-releases.git#v7.0.0-wvvmp-beta.6",
  "electron-builder": "^21.2.0",
}
```

**Comment by khwaaj** [comment]
I didn't see your latest additions in time for my comment above, the only thing you should need to change is the electronDownload config AFAICT.

**Comment by Tal-telecomsante** [comment]
That's perfectly work with 

"electronDownload": {
    "mirror": "https://github.com/castlabs/electron-releases/releases/download/v"
 }

Thank you for your help ;)
