### ISSUE TITLE
Electron 7.0.0 - wrong mirrorOptions url in install.js

### ISSUE THREAD

**Issue by jeremco** [castlabs/electron-releases#45]
Hi,

I am trying to install electron v7.0.0-wvvmp using package.json : 

"electron": "git+https://github.com/castlabs/electron-releases#v7.0.0-wvvmp"

But installation failed : 
node install.js

(node:15582) UnhandledPromiseRejectionWarning: RequestError: connect ECONNREFUSED 140.82.118.4:443
    at ClientRequest.request.once.error (....

Using electron 6.1.x, in install.js script, the mirrorOptions is "https://github.com/castlabs/electron-releases/releases/download/v" whereas for electron 7.0.0 it is "https://github.com/castlabs/electron-releases/releases/download/"

Can you check please

Jérémie

**Comment by khwaaj** [comment]
Hi Jérémie,

Interestingly, I actually had to change the mirror URL for electron 7, removing the `v`, to make it work after they migrated to using `@electron/get` instead of `electron-download` in the install script. If I add the extra `v` I get a 404 error when running `npm install`.

Not sure why you have the opposite behaviour, but maybe it could be some kind of version-issue with the tools in use. The machine I'm testing on right now runs macOS Mojave with `node v12.13.0` and `npm 6.12.0`, what is your setup?

Emil

**Comment by jeremco** [comment]
Hi, 

Thanks for explanation.
I am using node v10.15.0 and npm 6.4.1.
I am also using macosx mojave

Maybe that's because i am behind a corporate proxy, but, it was ok for old versions

**Comment by khwaaj** [comment]
Well, I'm not sure about the corporate proxy role in this since it usually works fine for you but ECONNREFUSED indicates the connection can't be established with the remote host, not that the target file can't be found, so I guess it is possible that something is interfering with the connection setup.

Actually I just found [this pull request](https://github.com/electron/get/pull/118), adding support for corporate proxies to `@electron/get`. The feature should be available in the latest release, although I've not dug into how to actually use it.

**Comment by jeremco** [comment]
Re, 

I have succeeded to download v7.
The problem was the proxy. I had to add 2 env variables : 

export ELECTRON_GET_USE_PROXY=true // to activate proxy for electron/get module
export GLOBAL_AGENT_HTTPS_PROXY=my_proxy to configure global agent proxy

Thanks
Jérémie

**Comment by khwaaj** [comment]
Glad to hear it!
