### ISSUE TITLE
Windows build error

### ISSUE THREAD

**Issue by IhorVimmi** [castlabs/electron-releases#46]
cannot resolve https://github.com/electron/electron/releases/download/v7.0.0-wvvmp-beta.3/electron-v7.0.0-wvvmp-beta.3-win32-x64.zip: status code 404

**Comment by khwaaj** [comment]
Looks like the download URL is wrong, it should not start with https://github.com/electron/electron/ but  https://github.com/castlabs/electron-releases/ to access our releases.

Are you using something like electron-builder when you are seeing this? If you are you can set the mirror options to make it download from the correct URL using something like [this](https://github.com/castlabs/electron-releases/issues/43#issuecomment-544548710) in your `package.json`.

**Comment by IhorVimmi** [comment]
@khwaaj thanks, that fix my issue) 

Also i have question about build for ubuntu on windows

 error=Get https://service.electron.build/find-build-agent?no-cache=1esnkel: dial tcp 51.15.76.176:443: connectex: A connection attempt failed because the connected party did not proper
ly respond after a period of time, or established connection failed because connected host has failed to respond.

Can I fix that?

**Comment by khwaaj** [comment]
@IhorVimmi, with so little context it is a bit difficult to figure out what you are trying to do and how you are going about it.

That said this appears to be an [electron-builder](https://github.com/electron-userland/electron-builder) issue, see https://github.com/electron-userland/electron-builder/issues/4318. There appears to be a some kind of temporary workaround merged that disables the linux build but it has not made it into any release that I can see.

Since this is a bit outside the scope of this project it is not something I am very familiar with so you are probably better off asking about it in some [electron-builder](https://github.com/electron-userland/electron-builder) forum.

**Comment by IhorVimmi** [comment]
@khwaaj thank you man) you save my time)
