### ISSUE TITLE
Widevine license

### ISSUE THREAD

**Issue by IhorVimmi** [castlabs/electron-releases#48]
Hi! I have an issue with getting widevine license
I did request to getting the license from widevine, on Linux all works correctly but on windows in the second request I getting "malformed" response, but in Chrome got the correct response.

**Comment by khwaaj** [comment]
Well, since I have very little detail on what you are using and doing it is hard to speculate about the cause. Electron version? Player software? Shaka Player? Direct custom EME? Etcetera...

One thing though that is different between Linux and Windows (or macOS) is that the Linux Widevine CDM does not support [VMP signing](https://github.com/castlabs/electron-releases#verified-media-path-vmp) and thus does not enforce it. Our releases come pre-signed with our VMP certificate for development but will not work against production servers. The signature we provide is also prone to be broken on Windows by tools such as electron-builder making changes to the executable, which means your application needs to be [re-signed](https://github.com/castlabs/electron-releases#re-signing) before Widevine can be successfully used. For now this requires that you enter into a [license agreement](https://github.com/castlabs/electron-releases#licensing) with Google Widevine to get your own VMP certificates.

To test if VMP is the cause of your issue it should work better if you don't actually package the application, but run it directly in your source tree. This allows the provided development VMP signature to work as long as you are not using production Widevine servers.

**Comment by IhorVimmi** [comment]
@khwaaj I'm using videojs vs electron ("electron": "https://github.com/castlabs/electron-releases#v7.1.1-wvvmp",) + angular  7.2

That is strange because it works on Ubuntu, and I haven't any ideas about that.

In chrome (windows) also works correctly

**Comment by khwaaj** [comment]
Ok, I'm not very familiar with videojs in this context but since you have it working in Chrome and Electron on Linux it should work fine.

Like I said before, one very likely explanation for your code working on Linux but not Windows is that VMP is not enforced on Linux. It is enforced on Windows and macOS though so if you are trying to access content from a production service it will fail since we are only allowed to provide public builds that are signed for development (I'm not sure how the ECDRM proxy you are using is configured though). Also, packaging the application on Windows with something like `electron-builder` is prone to break the VMP signature since it alters the signed executable, which would make all Widevine DRM requests fail. The reason your code works in Chrome is that it comes pre-signed with Googles own production VMP certificates (and you are not likely to break it by accident).

To make a build of Electron that is guaranteed to work in all situations *you need your own VMP certificate from Google*, as is explained in the [README](https://github.com/castlabs/electron-releases/blob/master/README.md), and then you need to re-sign your product as the last step when packaging it.
