### ISSUE TITLE
Video's dont play

### ISSUE THREAD

**Issue by locomain** [castlabs/electron-releases#54]
Maybe i am doing this wrong but i cant seem to get netflix videos to play using a BrowserView.
This is the code that i use:
`    let browser = new BrowserView({ webPreferences: {
        plugins: true
    }});
    const toolbarHeight = Platform.isWindows()? 75 : 65;
    browser.setAutoResize({width: true, height: true});
    mainWindow.addBrowserView(browser);`

I added this to my package.json: 

"electron": "https://github.com/castlabs/electron-releases#v7.1.14-wvvmp"

The widevine-ready event is triggered.
The widevine-error event is not triggered

**Comment by khwaaj** [comment]
Since you don't mention signing the build with a VMP certificate I would assume that is your issue, please correct me if that assumption is wrong. For production services, such as Netflix, you'd currently need your own VMP production certificate to sign your build. The builds provided here are only VMP signed for development and some scenarios even break that signature.

If you take a look at the [README](https://github.com/castlabs/electron-releases/blob/v7.1.14-wvvmp/README.md) you'll find more information about this, particularly in the [Verified Media Path (VMP)](https://github.com/castlabs/electron-releases/blob/v7.1.14-wvvmp/README.md#verified-media-path-vmp) section.
