### ISSUE TITLE
Why don't you have anything that tells me how to install this?

### ISSUE THREAD

**Issue by kassimir** [castlabs/electron-releases#55]
Isn't that what the readme and wiki is for? Or am I crazy?

Nothing shows me how to install this. Is it magic? Is it an npm install? 

I tried replacing 

```
 "dependencies": {
   "electron": "^8.2.1"
 } 
```

with

```
  "devDependencies": {
    "electron": "https://github.com/castlabs/electron-releases"
  }
```
and got this: "Error: Generated checksum for 'electron-v9.0.0-wvvmp-beta.16-win32-x64.zip' did not match expected checksum." I tried cloning it and running install.js, and it gives me the error "Error: Generated checksum for 'electron-v9.0.0-wvvmp-beta.16-win32-x64.zip' did not match expected checksum." That's probably because that file doesn't exist. I don't have any .zip files right now, because I'm actively working on my project. Which I can't do, if it's in a .zip file. I thought maybe it only works for compiled projects (which... I mean... why?!), but I don't have a single .zip file in my compiled projects either. 

How the hell am I supposed to use this?!

**Comment by kassimir** [comment]
Good news. After trying every release tag, I finally got this one to install: `https://github.com/castlabs/electron-releases#v9.0.0-wvvmp-beta.2` Unfortunately, Netflix still tells me "This title is not available to watch instantly. Please try another title" on every title. Cool.

**Comment by kassimir** [comment]
New update. I decided to try loading Netflix into the parent window (BrowserWindow) instead of the child window (BrowserView) (they both have `plugins: true` set), and now when I try to play something, it just goes to a black screen. No errors though. I guess that's progress. Unless you count the security warnings in the console? Maybe Netflix is trying to hack me.

**Comment by kassimir** [comment]
Oh, man. My favorite update so far. After looking at the table on the wiki again, I realized there are 3 stable versions. Here I was trying to use version 9 when it's still in TBD! So I went ahead and switched over to 8.2.2. Installed fine. YES! Went to run my program, and I got this fantastic error: "Error: spawn [path]\node_modules\electron\dist\Electron.app\Contents\MacOS\Electron ENOENT"

Yeah, you're never gonna find that on my Windows PC, bud. Maybe look for the windows one? I don't know. Again, maybe I'm crazy.

**Comment by kassimir** [comment]
Same error with version 7.2.2.

You know people still use Windows, right?

**Comment by kassimir** [comment]
Okay... well I just read through another issue that says I need my own VMP certificate to play Netflix videos?! It would appear this has been all for naught. Well... I'd like to say it's been fun. It hasn't.

**Comment by khwaaj** [comment]
Hi @kassimir,

I'm sorry you have been experiencing issues.

First off, instructions for installing and using our releases are available in [README.md](https://github.com/castlabs/electron-releases/blob/master/README.md) at the root of the repository, not in the Wiki where only some general information lives currently. The README also explains the requirements for VMP and development/production signing. As you discovered you need your own VMP certificate to be able to use Widevine outside of development scenarios. We are working with the Widevine team to find a better solution here, but this is currently a requirement that we have to abide by.

Second, it appears that the latest release in each of the series had a bad checksum file published due to an issue when moving to a new machine for publishing, that is why you had trouble with the installations. Earlier releases are fine though. I've fixed the faulty releases but the electron installer may have cached the downloads so you'll need to clear the cache to get the installation to work if you want to try again (e.g. removing the contents of ~/AppData/Local/electron/Cache on Windows).

As it seems you have given up on this endevour I'll close the issue, feel free to reopen if you still need help but I would appreciate it if we could keep a more civil tone in the discussion.

Best,
Emil
