### ISSUE TITLE
CDM on Windows reporting Tampered status

### ISSUE THREAD

**Issue by turbidwater** [castlabs/electron-releases#57]
I have an Electron app for playing DRM assets. On Mac it is working well. On PC it plays back fine, but the license server is getting a response that says the platform status is PLATFORM_TAMPERED. 

I read through the issue here: https://github.com/castlabs/electron-releases/issues/22, but my digests match and I'm getting no errors when running the vmp_resign.py script. 

I'm using electron-builder to build and sign the application, then using the vmp_resign script afterwards. I have tried turning off the signAndEditExecutable option so it's not inserting icons and metadata, but I still am getting the tampered status. It sounds like running the resign script after electron-builder completes may not be enough, based on this: https://github.com/castlabs/electron-releases/issues/56#issuecomment-635600098

One thing I do notice that is odd, is that the CDM version reported in the response is one patch version off of what the manifest.json that accompanies the CDM says. The response has "4.10.1582.1", whereas the manifest.json has "4.10.1582.2". However, I feel that may be a red herring, as on Mac it is doing the same thing and receiving a VERIFIED status.

Here is the output from the resign verification:
```$ ./node_modules/electron/vmp-resign.py -M "My Player.exe" -vv -Y build
vmp-resign/WARNING: -K/--key, -P/--password, -n/--no-prompt-password and -p/--prompt-password are ignored for verification
vmp-resign/INFO: Verifying package: build
vmp-resign/INFO: Reading signature from: build\My Player.exe.sig
vmp-resign/DEBUG: Decoding signature file with version: 0
vmp-resign/DEBUG: Decoding certificate entry
vmp-resign/DEBUG: Decoding signature entry
vmp-resign/DEBUG: Decoding flags entry
vmp-resign/DEBUG: Certificate:
vmp-resign/DEBUG:   Version: v3
vmp-resign/DEBUG:   Serial Number: <REDACTED>
vmp-resign/DEBUG:   Signature Hash Algorithm: sha256
vmp-resign/DEBUG:   Issuer: C=US, ST=Washington, L=Kirkland, O=Google, OU=Widevine, CN=widevine-codesign-root-ca
vmp-resign/DEBUG:   Subject: C=FR, L=Srasbourg, O=Movidone
vmp-resign/DEBUG:   Not Before: 2019-03-04 22:43:01
vmp-resign/DEBUG:   Not After: 2029-03-01 22:43:01
vmp-resign/DEBUG:   Extensions:
vmp-resign/DEBUG:     Subject Key Identifier:
vmp-resign/DEBUG:       Digest: c84c5b76507d9fcbe12195414e85b8727b330adc
vmp-resign/DEBUG:     Authority Key Identifier:
vmp-resign/DEBUG:       Key ID: ca3dd88e0f74577fd09ad9e121bf42fb23552986
vmp-resign/DEBUG:     Basic Constraints:
vmp-resign/DEBUG:       CA: False
vmp-resign/DEBUG:     Key Usage:
vmp-resign/DEBUG:       Digital Signature
vmp-resign/DEBUG:     Extended Key Usage:
vmp-resign/DEBUG:       Code Signing
vmp-resign/DEBUG:     1.3.6.1.4.1.11129.4.1.3:
vmp-resign/DEBUG:       ...
vmp-resign/DEBUG: Public Key: RSA 2048 bit
vmp-resign/INFO: Verifying file: build\My Player.exe
vmp-resign/DEBUG: File digest: c5f88e8f18dc1c5c62ab5905d8410ed90446f2be1249b3bb19403c1d8753514d61de0bd0ff3a08057925cd49fdaecda5dc790cf63642336d2d2eb6c39a0ae288
vmp-resign/DEBUG: Verifying data: c5f88e8f18dc1c5c62ab5905d8410ed90446f2be1249b3bb19403c1d8753514d61de0bd0ff3a08057925cd49fdaecda5dc790cf63642336d2d2eb6c39a0ae28801
vmp-resign/INFO: Verified package: build
```

Here is the status from the CDM with the tampered status:
```json
{
   "status":"OK",
   "status_message":"",
   "license_metadata":{
      "content_id":"ewyxzy9KDEGb\/jG65VbVFA==",
      "license_type":"OFFLINE",
      "request_type":"NEW"
   },
   "supported_tracks":[
      {
         "type":"HD",
         "key_id":"TjRfOpWvU4erQnemQaeqgA==",
         "video_feature":""
      },
      {
         "type":"SD",
         "key_id":"RfIwY9PTUICi7o3daBn8cA==",
         "video_feature":""
      },
      {
         "type":"AUDIO",
         "key_id":"KRBtTL AVyKwylcrnLXI0A==",
         "video_feature":""
      }
   ],
   "make":"Google",
   "model":"ChromeCDM-Windows-2",
   "security_level":3,
   "internal_status":0,
   "session_state":{
      "license_id":{
         "request_id":"sNQeQDTN0PBnxn4WA3pW8g==",
         "session_id":"sNQeQDTN0PBnxn4WA3pW8g==",
         "purchase_id":"",
         "type":"OFFLINE",
         "version":0
      },
      "signing_key":"<REDACTED>",
      "keybox_system_id":13701,
      "license_counter":0
   },
   "drm_cert_serial_number":"<REDACTED>",
   "device_whitelist_state":"DEVICE_NOT_WHITELISTED",
   "platform":"chrome",
   "device_state":"RELEASED",
   "pssh_data":{
      "key_id":[
         "<REDACTED>"
      ],
      "content_id":"ewyxzy9KDEGb\/jG65VbVFA=="
   },
   "client_max_hdcp_version":"HDCP_V1",
   "client_info":[
      {
         "name":"architecture_name",
         "value":"x86-64"
      },
      {
         "name":"company_name",
         "value":"Google"
      },
      {
         "name":"model_name",
         "value":"ChromeCDM"
      },
      {
         "name":"platform_name",
         "value":"Windows"
      },
      {
         "name":"widevine_cdm_version",
         "value":"4.10.1582.1"
      }
   ],
   "platform_verification_status":"PLATFORM_TAMPERED",
   "content_owner":"movidone",
   "content_provider":"movidone",
   "system_id":13701,
   "oem_crypto_api_version":0,
   "resource_rating_tier":0,
   "client_ip":"<REDACTED>"
}
```

Any advice on how to change my signing process or configuration to resolve this tampered status?

**Comment by khwaaj** [comment]
This typically happens when the VMP signature has been broken, i.e. the electron executable has been changed somehow after you re-signed it. Not sure what can have caused it in this particular case though.

The verification output above, is that printed during build or is it something you have manually done after? If it is part of the build I would suggest trying it on the final package to see if it still passes the verification, i.e. unzipping the final package and using the same verification on the extracted version of the application. If it fails we'd know something happened to the executable in between the two verifications. Are you perhaps code-signing the application after the build process? This is another thing that changes the executable in a way that breaks VMP.

I would not worry too much about the version discrepancy you are seeing with `manifest.json`. Some previous releases have had this same issue where the version number was not updated correctly in all places.

**Comment by turbidwater** [comment]
The verification output is from after I was completely done with the build process. I'm building and signing the app using electron-builder, and then resigning Electron using the vmp-resign script after that process completes. For Mac, I was using vmp-resign on Electron before building and signing with electron-builder. It was my understanding that I had to do this in the opposite order for PC. 

I'm not entirely certain of the order of operations performed by electron-builder. I would assume it first builds the app, then signs the exe. I suppose the vmp-resign running after that completes could break the signing, but I'm not sure where in the electron builder process I would need to try to run the vmp-resign to sign Electron.

**Comment by khwaaj** [comment]
Yes, you are right. On Windows you need to VMP-sign after anything that changes the executable, which can be electron-builder itself, code-signing or something else. On the Mac the situation is different since code-signing takes the entire app package into account, which means you need to do that after the VMP signature file has been added (and VMP can even account for some, non-code, Mach-O executable sections changing after then signing).

It sounds like you are doing everything right, but `PLATFORM_TAMPERED` indicates that VMP has found some issue in the VMP signature chain. Exactly what causes it is difficult to say without examining the entire process leading up to it.

I'm not sure what kind of advice I can currently give around `electron-builder`. It has been a long time since I last used it for anything and I know things have changed substantially since then. IIUC they now have some new hooks that should make integrations easier, so perhaps it is time I took a closer look at them :-)

Btw, what version of Electron are you using?

**Comment by turbidwater** [comment]
Thanks, @khwaaj. I am using 8.3.0. 

I will ask the electron-builder folks if they have any leads. Info on a PLATFORM_TAMPERED status is scarce out there on the Web.

**Comment by khwaaj** [comment]
Ok, v8.3.0-wvvmp is working fine for me, so there appears to be nothing wrong with the release.

I put together a simple project where I tested `electron-builder` and I think I have a something that should work for cases such as yours, unless I have misunderstood what you are trying to do. I can't test it completely since I don't have code-sign certificates here, but aside from that it does what it should and produces correctly signed assets on macOS and Windows (that do not get `PLATFORM_TAMPERED` on any platform).

I can't share the whole project at this point since it is built on top of a private project but I can share the essentials of what I did:

`package.json`
```json
{
  "name": "electron-builder-wvvmp",
  "version": "1.0.0",
  "description": "A minimal Electron application with Widevine support",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "dist:mac": "electron-builder --mac",
    "dist:win": "electron-builder --win --x64 --ia32"
  },
  "author": "castLabs",
  "devDependencies": {
    "electron": "git+https://github.com/castlabs/electron-releases.git#v8.3.0-wvvmp",
    "electron-builder": "^22.7.0"
  },
  "build": {
    "appId": "electron.builder.wvvmp",
    "electronDownload": {
      "mirror": "https://github.com/castlabs/electron-releases/releases/download/v"
    },
    "mac": {
      "target": "zip"
    },
    "linux": {
      "target": "zip"
    },
    "win": {
      "target": "zip",
      "icon": "build/icon.ico"
    },
    "afterPack": "./after-pack.js",
    "afterSign": "./after-sign.js"
  },
  "dependencies": {}
}

```

`after-pack.js`
```js
exports.default = async function(context) {
  // If we are not packaging for mac we don't sign here, just return
  if (context.packager.platform.name !== 'mac') {
    return;
  }

  // Sign the application package
  var spawnSync = require("child_process").spawnSync;
  var vmp = spawnSync('python', [
      'node_modules/electron/vmp-resign.py',
      '-vv',
      '-M', context.packager.appInfo.productFilename + '.app',
      '-C', 'path/to/cert.pem',
      '-K', 'path/to/key.pem',
      '-p', // Prompt for password (use -P to supply instead)
      context.appOutDir
    ],
    {
      stdio: 'inherit' 
    });

  if (vmp.status != 0) {
    throw new Error('vmp-resign.py failed with code: ' + vmp.status);
  }

}
```

`after-sign.js`
```js
exports.default = async function(context) {

  // If we are not packaging for windows we don't sign here, just return
  if (context.packager.platform.name !== 'windows') {
    return;
  }

  // Make sure we don't leave an outdated electron.exe.sig laying about
  if (context.packager.appInfo.productFilename !== 'electron') {
    var fs = require("fs");
    var path = context.appOutDir + '/electron.exe.sig'
    if (fs.existsSync(path)) {
      fs.unlinkSync(path)
    }
  }

  // Sign the application package
  var spawnSync = require("child_process").spawnSync; 
  var vmp = spawnSync('python', [
      'node_modules/electron/vmp-resign.py',
      '-vv',
      '-W', context.packager.appInfo.productFilename + '.exe',
      '-C', 'path/to/cert.pem',
      '-K', 'path/to/key.pem',
      '-p', // Prompt for password (use -P to supply instead)
      context.appOutDir
    ],
    {
      stdio: 'inherit' 
    });

  if (vmp.status != 0) {
    throw new Error('vmp-resign.py failed with code: ' + vmp.status);
  }

}
```

With this I can use `npm run dist:mac && npm run dist:win` to build Mac and Windows packages, and `node_modules/electron/vmp-resign.py -vv -Y -M electron-builder-wvvmp.app -W electron-builder-wvvmp.exe dist/mac dist/win-unpacked dist/win-ia32-unpacked` to verify them all in one go (on my Mac, on Windows I can only build Windows packages).

I hope this gives you some ideas on how to work around the issue you are seeing in your project!

**Comment by simongregory** [comment]
On spotting this thread yesterday I took a look at our monitoring for tampered messages and found just over 500 reports in the previous 24 hours. These were tied to a recent release so, worrying about code signing (even though there's plenty of monitoring evidence the build works) I double checked the build on a Win 10  Pro v1903 18362.836 machine. It failed with a tampering message. Back on another Windows 10 machine the same build worked. So far the only noted difference is the OS build number - 18362.592

So, going back to #52, I altered the `--widevine-base-dir=C://foo` on the "tampered" machine and it worked. Looking at the app support folder it's reported as `C:\Users\simongregory\AppData\Roaming\AppName` which turns out to be an alias to `C:\Users\simongregory\AppData\Local\AppName`. I expect this is the cause of the trouble (as discussed back in #50) - and may well be one thing to rule out here. It's also looking like the scope of #50 extends beyond windows store installs.

**Comment by khwaaj** [comment]
Interesting, not really sure of what prompts the extra alias in AppData though. My test rig currently runs Win 10 Pro v1909 18363.836, and I've not seen any problems there, so far. Maybe it has something to do with the OS version that first created the AppData folders.

If this indeed just an alias, and not something like the overlay filesystem that the Desktop Bridge uses, it might be possible to simply determine the real path before registering the CDM. I'll try to set up some testing around this.

**Comment by simongregory** [comment]
If thats the case then my first thought is that I manually created the alias/shortcut earlier in the year to test with and have forgotten about doing it! Let me investigate with a clean install.

**Comment by turbidwater** [comment]
I'm also on Win 10 Pro v1909 18363.836. This issue came up from a build made back in October 2019 on electron 5.0.0-beta. It's now upgraded to 8.3.0, and the issue persists. I've tried installing it on a completely clean machine that is up to date, and the issue still persists there, so my suspicion would not be the version of OS that made the AppData folder. I will see if I have the same sort of aliasing or if changing the widevine-base-dir helps. Thanks for the extra info guys!

**Comment by simongregory** [comment]
I've been unable to recreate the alias through fresh installs and rolling back to earlier versions of the app and upgrading again. I think it was almost certainly me who created it in the first place. Apologies for the red-herring.

I'm still nowhere accounting for the tampering messages in monitoring though. For us it means a license isn't issued and users cant watch content - I have one user contact that appears to be getting this issue so will follow up with them and let you know if there's anything useful.

**Comment by khwaaj** [comment]
Ok, thanks @simongregory, the AppData aliasing seems more unlikely as a cause then. Still, this appearance of `PLATFORM_TAMPERED` in your logs has me worried this can become a widespread issue. The fact that some instances of the same version seem to work while others don't seems to point to something on the systems, or perhaps the service, rather than in the application package.

@turbidwater, did you see any indication that your package works on some machine but not others? Maybe you have some package exhibiting the problem that you can share with me, here or privately, so that I can see if I can reproduce the problem here?

**Comment by turbidwater** [comment]
@khwaaj It has not worked on the 4 PCs we have tested on. Two of those are Win 10 Pro v1903 18362.836.  So it has not seemed to change from PC to PC. 

I will see if I can generate a generic app that exhibits the behavior, but the current project cannot be shared, unfortunately.

**Comment by turbidwater** [comment]
Oh, and I did verify that there is no aliasing happening on my AppData folders, so yes, that would appear to not be the cause.

**Comment by turbidwater** [comment]
I have filed an issue with electron-builder as well: https://github.com/electron-userland/electron-builder/issues/5038
I tried updating to the most recent version, but got the same results. So I'll cross post it here.

**Comment by khwaaj** [comment]
@turbidwater, after reading through this and #56 again I just need to clarify a few of things.

In #56 you mention signing `./node_modules/electron/dist` with `vmp-resign.py`, which is fine, and even a requirement if you need to run the application directly from the repo with production VMP support (e.g. using `npm run start` or something similar).

In the config posted in https://github.com/electron-userland/electron-builder/issues/5038 you are passing `electronDist` to `electron-builder` to use the, possibly re-signed, version of electron in `./node_modules/electron/dist` (as opposed to downloading/extracting a fresh package, which is the default). This is also fine, and should even work with `electron-builder` for the Mac version of your package, except in very special cases, as long as the signing is done before `electron-builder` does its thing. It's not likely work for a Windows though, unless you can configure `electron-builder` to leave the executable entirely untouched, which I'm not certain if it's even possible. And even then you'd need to manually rename `electron.exe.sig` to match the new application executable name before `electron-builder` creates the final packaged artifacts.

I'm not sure if this is representative of the signing you are currently doing, especially since you do mention that you actually re-sign after the application is built and code-signed, but you do not mention how you accomplish this. Re-signing after `electron-builder` has produced the final artifacts is unpractical since you'd have to extract/re-sign/re-package the artifacts themselves. A better approach would be to use the `afterPack` and `afterSign` hooks that I use in my example above, but I'm not sure if you are doing this, and your example posted in https://github.com/electron-userland/electron-builder/issues/5038 doesn't appear to do so as it's calling `notarize.js` in `afterSign`, so I'm not sure what to think here.

Also, since `electron-builder` copies electron, e.g. to `dist/win-unpacked` for `win32-x64` by default, and then renames/processes the copy before packaging it into the final artifacts, that is the path you'd need to re-sign, not `node_modules/electron/dist`. The actual path used is available in the `context` passed to the `afterPack`/`afterSign` hooks (see `context.appOutDir` as used in my example scripts above), as are a few other useful values.

Since you are seeing the same error on all machines you have tried I'm still inclined to believe something is actually wrong with the VMP signature of the application, as opposed to the problems that @simongregory has been seeing in their logs lately. My suggestion would be to try and adopt something similar to the scripts I posted above for the `afterPack` and `afterSign` hooks, merging the latter with your `notarize.js` script so that it can both sign and notarize depending on the platform.

**Comment by turbidwater** [comment]
Thanks, @khwaaj. Those are solid suggestions. 

For PC, I am re-signing the electron in the app, rather than the node_modules version. 
`./node_modules/electron/vmp-resign.py -C "VMP\Signed by widevine\prod-movideon.der" -P "MyPassword" -K  ./VMP/production-key.pem -W "MyPlayer.exe" -v build`

But that's probably the problem. I think your idea of moving the signing step forward in the process to the `afterPack` and `afterSign` hooks seem like good ones. I will give those a try.

**Comment by simongregory** [comment]
Quick update - Tamper message rate is down to around 300. Am unsure what conclusion to draw from that, its unlikely users are going to persist with the app if it's started failing so it could suggest something system specific with a limit.

User contact is on Win 7 and not technical. They claim it always worked before and don't know when it stopped exactly. They have a single user account, run Norton Antivirus, it's not a work PC (can have security restrictions and proxies), don't use Windows OneDrive/use cloud backup. I'm asking them to try setting a `--widevine-base-dir` to rule out folder aliasing. It's 50/50 as to wether they'll respond.

There are a lot of moving parts here, I was warned earlier in the year our licence supplier was upgrading (all went fine with QA), but the service is another thing I'm following up.

**Comment by khwaaj** [comment]
@simongregory, thanks for the update.

I agree it is hard to draw any conclusions currently. There are any number of things that could go wrong on both the client-side and server-side of things, so it would certainly have helped a lot with a technically inclined user to perform some tests locally on a failing setup. I hope you can get a response on the test you requested, at least.

**Comment by turbidwater** [comment]
@khwaaj , thank you again! Moving the re-sign into the afterSign step appears to have fixed the VMP. I'm no longer seeing the TAMPERED status. That script is now split into Mac and PC versions where for PC it runs vmp-resign and for Mac it runs notarizing. 

Now the only puzzle is that the exe.sig file doesn't appear to get regenerated. It may just be that the actual app code hasn't changed since my last build. Electron-builder is doing the renaming of the sig file and electron. 

I'm also getting a stern warning dialog when I install it where I have to, but I think that may have to do with the nature of the signing cert we're using. I'll have to dig into that.

But thanks so much (again) for your fantastic help and responsiveness!

**Comment by khwaaj** [comment]
Good to hear!

When you say the `exe.sig`-file doesn't get regenerated, are you talking about `electron.exe.sig` or your renamed `MyApp.exe.sig`? The latter should be there after your signing in `afterSign` but the former is redundant once the application has been renamed, which is why I remove it in my example script above. `electron-builder` has no knowledge of this and just leaves `electron.exe.sig` as is.

Not sure about the warning dialog you mention, but it sounds like it could have something to do with the code-signing, as you speculate. I hope it works out.

**Comment by turbidwater** [comment]
Yes, sorry. I meant the sig file for the app `MyPlayer.exe.sig`.

**Comment by turbidwater** [comment]
This seems to be fixed. Thanks a million, @khwaaj !

**Comment by coreybruce** [comment]
> Ok, v8.3.0-wvvmp is working fine for me, so there appears to be nothing wrong with the release.
> 
> I put together a simple project where I tested `electron-builder` and I think I have a something that should work for cases such as yours, unless I have misunderstood what you are trying to do. I can't test it completely since I don't have code-sign certificates here, but aside from that it does what it should and produces correctly signed assets on macOS and Windows (that do not get `PLATFORM_TAMPERED` on any platform).
> 
> I can't share the whole project at this point since it is built on top of a private project but I can share the essentials of what I did:
> 
> `package.json`
> 
> ```json
> {
>   "name": "electron-builder-wvvmp",
>   "version": "1.0.0",
>   "description": "A minimal Electron application with Widevine support",
>   "main": "main.js",
>   "scripts": {
>     "start": "electron .",
>     "dist:mac": "electron-builder --mac",
>     "dist:win": "electron-builder --win --x64 --ia32"
>   },
>   "author": "castLabs",
>   "devDependencies": {
>     "electron": "git+https://github.com/castlabs/electron-releases.git#v8.3.0-wvvmp",
>     "electron-builder": "^22.7.0"
>   },
>   "build": {
>     "appId": "electron.builder.wvvmp",
>     "electronDownload": {
>       "mirror": "https://github.com/castlabs/electron-releases/releases/download/v"
>     },
>     "mac": {
>       "target": "zip"
>     },
>     "linux": {
>       "target": "zip"
>     },
>     "win": {
>       "target": "zip",
>       "icon": "build/icon.ico"
>     },
>     "afterPack": "./after-pack.js",
>     "afterSign": "./after-sign.js"
>   },
>   "dependencies": {}
> }
> ```
> 
> `after-pack.js`
> 
> ```js
> exports.default = async function(context) {
>   // If we are not packaging for mac we don't sign here, just return
>   if (context.packager.platform.name !== 'mac') {
>     return;
>   }
> 
>   // Sign the application package
>   var spawnSync = require("child_process").spawnSync;
>   var vmp = spawnSync('python', [
>       'node_modules/electron/vmp-resign.py',
>       '-vv',
>       '-M', context.packager.appInfo.productFilename + '.app',
>       '-C', 'path/to/cert.pem',
>       '-K', 'path/to/key.pem',
>       '-p', // Prompt for password (use -P to supply instead)
>       context.appOutDir
>     ],
>     {
>       stdio: 'inherit' 
>     });
> 
>   if (vmp.status != 0) {
>     throw new Error('vmp-resign.py failed with code: ' + vmp.status);
>   }
> 
> }
> ```
> 
> `after-sign.js`
> 
> ```js
> exports.default = async function(context) {
> 
>   // If we are not packaging for windows we don't sign here, just return
>   if (context.packager.platform.name !== 'windows') {
>     return;
>   }
> 
>   // Make sure we don't leave an outdated electron.exe.sig laying about
>   if (context.packager.appInfo.productFilename !== 'electron') {
>     var fs = require("fs");
>     var path = context.appOutDir + '/electron.exe.sig'
>     if (fs.existsSync(path)) {
>       fs.unlinkSync(path)
>     }
>   }
> 
>   // Sign the application package
>   var spawnSync = require("child_process").spawnSync; 
>   var vmp = spawnSync('python', [
>       'node_modules/electron/vmp-resign.py',
>       '-vv',
>       '-W', context.packager.appInfo.productFilename + '.exe',
>       '-C', 'path/to/cert.pem',
>       '-K', 'path/to/key.pem',
>       '-p', // Prompt for password (use -P to supply instead)
>       context.appOutDir
>     ],
>     {
>       stdio: 'inherit' 
>     });
> 
>   if (vmp.status != 0) {
>     throw new Error('vmp-resign.py failed with code: ' + vmp.status);
>   }
> 
> }
> ```
> 
> With this I can use `npm run dist:mac && npm run dist:win` to build Mac and Windows packages, and `node_modules/electron/vmp-resign.py -vv -Y -M electron-builder-wvvmp.app -W electron-builder-wvvmp.exe dist/mac dist/win-unpacked dist/win-ia32-unpacked` to verify them all in one go (on my Mac, on Windows I can only build Windows packages).
> 
> I hope this gives you some ideas on how to work around the issue you are seeing in your project!

This is the issue with building for Mac even with those changes you gave me and the command to build for Windows and Mac

```
npm run dist:mac && npm run dist:win                          ✔  11s  

> Binge@1.0.0 dist:mac
> electron-builder --mac

  • electron-builder  version=22.14.5 os=5.10.93-1-MANJARO
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  ⨯ Cannot find module 'dmg-license'
Require stack:
- /mnt/Storage/Electron-applications/Binge/node_modules/dmg-builder/out/dmgLicense.js
- /mnt/Storage/Electron-applications/Binge/node_modules/dmg-builder/out/dmg.js
- /mnt/Storage/Electron-applications/Binge/node_modules/dmg-builder/out/dmgUtil.js
- /mnt/Storage/Electron-applications/Binge/node_modules/app-builder-lib/out/macPackager.js
- /mnt/Storage/Electron-applications/Binge/node_modules/app-builder-lib/out/packager.js
- /mnt/Storage/Electron-applications/Binge/node_modules/app-builder-lib/out/index.js
- /mnt/Storage/Electron-applications/Binge/node_modules/electron-builder/out/builder.js
- /mnt/Storage/Electron-applications/Binge/node_modules/electron-builder/out/cli/cli.js
- /mnt/Storage/Electron-applications/Binge/node_modules/electron-builder/cli.js  failedTask=build stackTrace=Error: Cannot find module 'dmg-license'
Require stack:
- /mnt/Storage/Electron-applications/Binge/node_modules/dmg-builder/out/dmgLicense.js
- /mnt/Storage/Electron-applications/Binge/node_modules/dmg-builder/out/dmg.js
- /mnt/Storage/Electron-applications/Binge/node_modules/dmg-builder/out/dmgUtil.js
- /mnt/Storage/Electron-applications/Binge/node_modules/app-builder-lib/out/macPackager.js
- /mnt/Storage/Electron-applications/Binge/node_modules/app-builder-lib/out/packager.js
- /mnt/Storage/Electron-applications/Binge/node_modules/app-builder-lib/out/index.js
- /mnt/Storage/Electron-applications/Binge/node_modules/electron-builder/out/builder.js
- /mnt/Storage/Electron-applications/Binge/node_modules/electron-builder/out/cli/cli.js
- /mnt/Storage/Electron-applications/Binge/node_modules/electron-builder/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/mnt/Storage/Electron-applications/Binge/node_modules/dmg-builder/src/dmgLicense.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/mnt/Storage/Electron-applications/Binge/node_modules/dmg-builder/src/dmg.ts:13:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/mnt/Storage/Electron-applications/Binge/node_modules/dmg-builder/src/dmgUtil.ts:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
```

If I try and install that missing module I run into this issue

```
npm i dmg-license                                               ✔ 
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for iconv-corefoundation@1.1.7: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/corey/.npm/_logs/2022-01-31T09_53_25_352Z-debug-0.log
```

**Comment by khwaaj** [comment]
The first error is apparently a know issue in a recent version of `electron-builder`, you should be able to find a workaround here: https://github.com/electron-userland/electron-builder/issues/6520#issuecomment-1003515465

The second issue is just that a required `python` module is not installed, specifically `macholib`. You should be able to install the requirement using `pip`, the python package handler. There is however another issue here since the `vmp-resign.py` can only be used if you are in possession of your own VMP certificate, which I'm assuming you are not since Google stopped issuing these quite some time back. You'll probably need to adapt the hooks to use the [EVS](https://github.com/castlabs/electron-releases/wiki/EVS) scripts instead to do the signing.

**Comment by coreybruce** [comment]
> The first error is apparently a know issue in a recent version of `electron-builder`, you should be able to find a workaround here: [electron-userland/electron-builder#6520 (comment)](https://github.com/electron-userland/electron-builder/issues/6520#issuecomment-1003515465)
> 
> The second issue is just that a required `python` module is not installed, specifically `macholib`. You should be able to install the requirement using `pip`, the python package handler. There is however another issue here since the `vmp-resign.py` can only be used if you are in possession of your own VMP certificate, which I'm assuming you are not since Google stopped issuing these quite some time back. You'll probably need to adapt the hooks to use the [EVS](https://github.com/castlabs/electron-releases/wiki/EVS) scripts instead to do the signing.

Ahh ok I see so I need to revert to a older version of electron-packager as a workaround, okay thanks for letting me know!

Oh ok, well that is a little bit of a issue than isn't it haha. I also notice that you have to maintain the signs which is really a pain since it says every month.

**Comment by khwaaj** [comment]
> I also notice that you have to maintain the signs which is really a pain since it says every month.

Yes, you need to update your authorization token periodically since it will expire otherwise. The tools automatically refresh this as long as possible (I don't remember the exact periods of the top of my head), but at some point you will need to re-authenticate using your credentials. In a CI scenario it is possible to provide these in the environment, or on the command line, as documented. If the tools are run in interactive mode (the default), you will be asked for credentials whenever required.

**Comment by coreybruce** [comment]
> > I also notice that you have to maintain the signs which is really a pain since it says every month.
> 
> Yes, you need to update your authorization token periodically since it will expire otherwise. The tools automatically refresh this as long as possible (I don't remember the exact periods of the top of my head), but at some point you will need to re-authenticate using your credentials. In a CI scenario it is possible to provide these in the environment, or on the command line, as documented. If the tools are run in interactive mode (the default), you will be asked for credentials whenever required.

Hmm ok I see, could I use one cert for all my packages needing it? it would make the whole process a lot easier as I maintain them all and they all come from me.

**Comment by khwaaj** [comment]
Yes, with [EVS](https://github.com/castlabs/electron-releases/wiki/EVS) you will only register an account. You can use this same account to sign whatever application you build on top of ECS.
