### ISSUE TITLE
Code signing failure using electron-vmp

### ISSUE THREAD

**Issue by jeremco** [castlabs/electron-releases#6]
Hi

We use this version of electron to build an application able to play downloaded streams (using downstream-electron) with persistent licence.
In dev, it is OK. 
But when we want to build the application, using electron-builder, there is an error with code signing. This error doesn't occurs with the official electron release. 

In the file I give, you will find 2 files packages.json, one pointing to your electron release, one pointing to official release. The sample is based upon electron-vue sample

[test_castlabs.zip](https://github.com/castlabs/electron-releases/files/1743629/test_castlabs.zip)

I have the error on MacOsx. To reproduce, you'll have to create a code signing certificate usig xcode (https://developer.apple.com/support/code-signing/), then try to build the application : 
npm install
npm run build

Jérémie

**Comment by khwaaj** [comment]
Hi Jérémie,

Thanks for your report. I’ve looked into this and it appears that the culprit is a stray symlink that is present in our release zip for some, still unclear, reason. I’ve removed it from the zip for the latest published release and will look into if the other releases have the same issue.

There are a couple of steps you need to take to make this effective locally since electron-downloader has local caching of the electron release packages, which will not be automatically updated:

1. Clear any cached 1.8.2-vmp1010 releases from ```~/.electron``` and ```~/Library/Caches/electron```
2. Clean & rebuild your product

Let me know if you have any more trouble!

Emil

**Comment by jeremco** [comment]
Hi 
It seems ok with your modifications.
Thanks a lot

Jérémie
