### ISSUE TITLE
Signature invalid: Certificate is valid for development only

### ISSUE THREAD

**Issue by mihaiav** [castlabs/electron-releases#73]
I'm trying to sign the the castlabs-electron fork app using the EVS service. The signing script is reporting a warning `Certificate is valid for development only`. What does this mean? How do I get a "production" certificate? 

```
Signing: dist/mac/nap.app
 - Verifying existing VMP signature
 - Signature invalid: Certificate is valid for development only
 - Requesting VMP signature
```

after_pack.js code

```
exports.default = async function(context) {
  // If we are not packaging for mac we don't sign here, just return
  if (context.packager.platform.name !== 'mac') {
    return;
  }
  // Sign the application package
  var spawnSync = require("child_process").spawnSync;
  var vmp = spawnSync('python', [
      '-m', 'castlabs_evs.vmp',
      'sign-pkg', 'dist/mac'
    ],
    {
      stdio: 'inherit' 
    });
  if (vmp.status != 0) {
    throw new Error('vmp-resign.py failed with code: ' + vmp.status);
  }
}
```

**Comment by khwaaj** [comment]
This is not a warning, just a statement about the current signature, i.e. the signature that exists (or does not exist) before EVS signs anything. It is just a check that is meant to avoid signing if there is already a valid signature fulfilling a specific set of requirements. So in this case the following happens:

1. A signature is requested by calling EVS with `sign-pkg`
2. The tool tries to evaluate the state of any existing signature
3. It determines the existing signature is for development only
4. Since valid signature was present, a new VMP signature is requested

If you run the tool a second time on the same package you should see different output where a new VMP signature is never requested since a valid one already exists.
