### ISSUE TITLE
Packaged app not getting VMP signed

### ISSUE THREAD

**Issue by jtvberg** [castlabs/electron-releases#77]
Using electron-builder, the output does not appear to be VMP signed (.dmg or .pkg) however, the .app in /dist/mac works just fine. Here is the afterPack script I am using:

```
exports.default = async function () {
  // Skip if not mac
  if (process.platform !== 'darwin') return

  const { exec } = require('child_process')
  exec('python3 -m castlabs_evs.vmp sign-pkg ./dist/mac')
}
```

I promise I beat my head on the desk for days and tried everything I could think of or find in the various docs before opening this issue. I appreciate your time.

Side note: thank you so much for EVS. I really appreciated the effort and the service.

**Comment by khwaaj** [comment]
A bit more detail about exactly what you are doing would help me diagnose this, like:
 - electron version
 - EVS script output & return code
 - any other steps done by your electron-builder configuration

Also, it would help if you could try to run `python3 -m castlabs_evs.vmp verify-pkg <path>` on both `dist/mac/` and the mounted resulting dmg, e.g. `/Volumes/<app-name> <app-version>/` and see what that output says.

**Comment by jtvberg** [comment]
Thank you for the quick reply.

Electron Version: v9.3.2-wvvmp
EVS does not give me output when building via electron-builder
Here is my electron-builder config (nothing else going on in `afterPack.js` but the code I pasted above):
 ```
 "build": {
    "appId": "com.jtvberg.streamdock",
    "copyright": "Copyright jtvberg",
    "electronDownload": {
      "mirror": "https://github.com/castlabs/electron-releases/releases/download/v"
    },
    "afterPack": "./afterPack.js",
    "mac": {
      "category": "public.app-category.productivity",
      "target": "dmg"
    },
    "publish": {
      "provider": "github"
    }
  }
```
On the dist/mac/ I get `- Signature is valid [streaming, min 90 days validity]`
On the mounted dmg I get `ValidityError: Certificate is valid for development only`
Seems like that is my problem but I can't figure out why the unpacked mac .app is getting signed but the packaged version is not.

**Comment by khwaaj** [comment]
Ok, so clearly `dist/mac` is signed properly but what ends up in the `dmg` is not actually the app that was signed.

I have a similar test setup where things are working, but maybe something changed in more recent versions of `electron-builder` (e.g. due to the addition of `arm64` support on macOS). Are there perhaps any other `dist/mac-*` directories? On windows different directories are used depending on the target architecture, so maybe something like this is happening here too now? Anyway, you should use the `appOutDir` provided in the `AfterPackContext` passed function to always ensure the correct output directory is signed, e.g:

```
exports.default = async function (ctx) {
  // Skip if not mac
  if (process.platform !== 'darwin') return

  const { exec } = require('child_process')
  exec('python3 -m castlabs_evs.vmp sign-pkg ' + ctx.appOutDir)
}
```

I'm not sure this is the issue here, but I think it is worth a shot.

**Comment by jtvberg** [comment]
Thank you for the tip. 
Tried it again but no love. Got the same output:
On the dist/mac/ I get - Signature is valid [streaming, min 90 days validity]
On the mounted dmg I get ValidityError: Certificate is valid for development only
I even tried using a .pkg and no luck there either.

**Comment by khwaaj** [comment]
Ah, I'm pretty sure I know what it is. The `exec` call is asynchronous, and the signing takes some time to complete, so `electron-builder` will just proceed to the next step - packaging the unsigned app. You should use `execSync` (or some manual synchronization) and it should work.

**Comment by jtvberg** [comment]
That makes a lot of sense. At one point I had the same suspicion but every thing I could find had the afterPack function set to async and I couldn't wrap my head around why the unpacked was good to go. Anyway, I tried just making the function not async but that didn't work either as I did not know about execSync!

Changed my code to:
```
exports.default = function (ctx) {
  // Skip if not mac
  if (process.platform !== 'darwin') return

  const { execSync } = require('child_process')
  execSync('python3 -m castlabs_evs.vmp sign-pkg ./dist/mac ' + ctx.appOutDir)
}
```
and BOOM! It works! 
Thank you so much khwaaj!

**Comment by khwaaj** [comment]
Nice, I'm happy you got it working.

Another tip, you should probably make sure you log the output from the script as well since it can contain valuable information if something goes wrong, or even if your authentication token has expired. With `execSync` you can do something similar to what is described here: https://stackoverflow.com/a/43077917

Alternatively, you could use `spawnSync`, similarly to what I do [here](https://github.com/castlabs/electron-releases/issues/57#issuecomment-639190660) with the old signing script, to let the subprocess inherit the parent stdio. This would also prompt you for your password if the token has expired, and you are running in an interactive terminal, unless you pass `-n` or `--no-ask` to the script.

**Comment by jtvberg** [comment]
Pro tips. Thank you, Emil!
