### ISSUE TITLE
Stuck at Requesting VMP signature

### ISSUE THREAD

**Issue by ryankashi** [castlabs/electron-releases#78]
Hi!

I am currently trying to resign my app after deleting my node_modules folder and rerunning npm install. I am operating on windows 10 using electron-forge

I have been able to previously code sign my work using:
`python -m castlabs_evs.vmp sign-pkg .\node_modules\electron\dist\`

during development, and then again for deployment:

`python -m castlabs_evs.vmp sign-pkg .\path\to\exe`

I have been able to successfully code sign on both Windows 10 as well as Big Sur operating systems, however I am now unable to use the service to code sign my software. I am using the castlabs version of electron 9.2.0, and I have not tested the signing service on my Mac build yet.

My Python version is Python 3.9.

**Comment by khwaaj** [comment]
There appears to be no service outage on my end, so signing should be possible. The service is running on AWS though, so with the recent problems they have been having this week there might have been temporary disruptions.

Are you seeing any output describing the error from the signing script, perhaps it is timing out after a while?

**Comment by ryankashi** [comment]
Okay I have no idea why but I have tried again today and everything works out fine. Perhaps it was a local outage or something?

**Comment by khwaaj** [comment]
Good to hear it is back to working for you!

And yes, with the AWS problems of the past week it is certainly possible that some local (or even global) anomalies occurred with the service, but we have not had any widespread reports. Since the signing involves a ~100MB upload even something like a significant slowdown of the upload speed from your location could be interpreted as a signing request getting "stuck", as it could potentially take an indeterminate amount of time to complete.

I will make sure we keep this in mind for any future updates of the scripts, and maybe consider adding some kind of progress indication during the upload to make such problems are more visible.
