### ISSUE TITLE
Issues with HBO Max when using Widevine

### ISSUE THREAD

**Issue by TheCleric** [castlabs/electron-releases#93]
I'm looking into https://github.com/nativefier/nativefier/issues/1153 and trying to determine the cause. We're packaging an Electron app based on your distribution (trying both 12.0.4 and 12.0.5), that contains a BrowserWindow pointed to `https://play.hbomax.com/`.

When trying to view content in this app, the video does not load, but instead displays:

> Can't Play Title
>
> Make sure your browser is not in private mode.

In the background the only event that fires is `widevine-ready` with version = '4.10.2209.1' and lastVersion = null

We are also listening for `widevine-update-pending` and `widevine-error` but neither of those are triggered.

Right before this occurs, the following request fails in the developer tools:

`POST https://comet.api.hbo.com/drm/license/widevine?keygen=playready&drmKeyVersion=2 400`

Interestingly enough, that is preceded by 1 successful call and followed with 1 successful call so I'm not sure if it's related:

![Screen Shot 2021-04-27 at 6 15 17 PM](https://user-images.githubusercontent.com/547567/116319489-9909a580-a784-11eb-9be1-9ec1ebec154e.png)

Let me know if there is any more info I can provide.

**Comment by khwaaj** [comment]
There are a number of things that could be the culprit here, so first a few questions:
1. On what platform does this happen? Multiple platforms?
2. Are you waiting for the `widevine-ready` event before opening the HBO Max URL in a browser window?
3. Are you using [EVS](https://github.com/castlabs/electron-releases/wiki/EVS) to VMP re-sign ECS for production use?
4. Do other commercial services work correctly?

Assuming the VMP signature is a correct production signature there are still some services that enforce other constraints, e.g. by checking the `User-Agent` string, and HBO Max has been mentioned in at least one other ticket, relating to this (see #80,  #91 might also be relevant). Actual verification that changing the `User-Agent` works in the case of HBO Max does not yet appear to be in any of the threads, but it might be worth a try.

**Comment by TheCleric** [comment]
I think we've got it worked out now, but to document for future use:

1. MacOS
2. Yes
3. I am now, and this seems to fix it.
4. Yes

As well I did try a few different User Agents, and this did not seem to have an affect. After signing, our default user agent works fine.
