### ISSUE TITLE
Hangs on Requesting VMP signature

### ISSUE THREAD

**Issue by deciacco** [castlabs/electron-releases#94]
Trying to sign a Nativefier electron with widevine app as per here (https://github.com/nativefier/nativefier/issues/1147#issuecomment-828597557) ... everything worked as far as creating account, etc. but it hangs on "Requesting VMP Signature". 

vmp.py 1.0.0rc5

```
d:\native>python -m castlabs_evs.vmp sign-pkg Udemy-win32-x64
Signing: Udemy-win32-x64\Udemy.exe
 - Verifying existing VMP signature
 - Signature invalid: Failed to verify signature
 - Requesting VMP signature
```

**Comment by khwaaj** [comment]
Are you sure it is hung, the process isn't instant since it involves uploading typically ~100MB of data to the signing service so it might take a while on a slower connection. The result is cached to speed up subsequent request that match the same executable.

In case you are on a slow connection passing `-z` might help a little bit since it enables gzip compression on the upload.

**Comment by deciacco** [comment]
you know, now that you mention that... you are mostly likely correct... I am on a slow connection at the moment whereas I'm usually not and I did not take that into account... I will let it run for a while and report back to verify... Thank you so much!

**Comment by deciacco** [comment]
That was it!!! I just needed to wait longer... Thank you so much!
