### ISSUE TITLE
Quite a Few Widevine based Apps no longer worker

### ISSUE THREAD

**Issue by pnegahdar** [castlabs/electron-releases#99]
Testing 13.0.1 and it seems like:

- Netflix
- Amazon Prime
- YoutubeTV
- Spotify

All have issues. Did something change? These were working recently.

**Comment by khwaaj** [comment]
It appears to work fine here. Which version of the Widevine CDM are you using, and did you disable updates of the CDM by any chance? Widevine is revoking all prior CDMs at the end of May, so it may just have happened (although officially it shouldn't until May 31st).

**Comment by pnegahdar** [comment]
Hmm doesn't seem like it. And we didn't change much, doing it on clean install and having the same issue. I'll follow up in the week with a more thorough write up. 

In the mean time, is EVS a requirement? We had never done it before and it seems like things just worked. Maybe we need it now?

**Comment by khwaaj** [comment]
Yes, EVS is a requirement for commercial services (and any service requiring VMP if the pre-generated signature is broken, e.g. during packaging). If it worked before there has been some misconfiguration somewhere on the server side because ECS is only pre-signed for development, and will not work with services requiring a production VMP signature out of the box.

**Comment by pnegahdar** [comment]
Thanks! I switched to use the EVS instructions you provided (amazing by the way, thank you thank you) and now I am getting a slightly less opaque error: 

![image](https://user-images.githubusercontent.com/833067/120127378-3b0a1c80-c18d-11eb-98c2-a05fd0e80841.png)

![image](https://user-images.githubusercontent.com/833067/120127410-4eb58300-c18d-11eb-99f6-9f97830cfd6b.png)

Also it isn't obvious to me what binary I need to pass to the `python3 -m castlabs_evs.vmp verify` and `python3 -m castlabs_evs.vmp verify-pkg` cli. I tried passing the path to the `.app` and it didn't work.

**Comment by khwaaj** [comment]
The error above indicates that the Widevine CDM has not been installed/registered properly. Are you waiting for the `widevine-ready` event before loading the page?

Typically you would only use the `sign-pkg`/`verify-pkg` commands (using `sign`/`verify` requires knowledge of exactly what needs to be signed, which differs between platforms). `sign-pkg`/`verify-pkg` takes the directory that contains the Electron `.app` or `.exe` as an argument, so if you have your app in `/my/package/Electron.app` you would pass `/my/package`.

**Comment by pnegahdar** [comment]
Ah! I see, it seems like the "Signing request failed", is there any way to see what this error means or what went wrong? Also happy to jump on a chat (Discord/slack/etc), if theres any way to debug this. 

```
stdErr: 
EVS Signing Application com.synth.app at /app/dist/electron/mac
Evs signing finished with
err: undefined
stdout: Signing: /app/dist/electron/mac/AppName.app
 - Verifying existing VMP signature
 - Signature invalid: Failed to read signature
 - Requesting VMP signature
HTTPError: Signing request failed: 400 Bad Request
 <- ValidityError: Binary signature denied
```

By the way it seems like this command can exit with a non zero exit code, which is why I missed it. Happy to send a PR when I figure this out. 

```
    console.log(`EVS Signing Application ${appId} at ${params.appOutDir}`)
    // % python3 -m castlabs_evs.vmp sign path/to/executable path/to/signature
    const signEvs = cp.spawnSync("python3", ["-m", "castlabs_evs.vmp", "sign-pkg", params.appOutDir], { encoding: "utf8" })
    console.log(`Evs signing finished with\nerr: ${signEvs.error}\nstdout: ${signEvs.stdout}\nstdErr: ${signEvs.stderr}`)
    if (signEvs.error) {
        process.exit(1)
    }
```

Really appreciate all the help!

**Comment by khwaaj** [comment]
"Binary signature denied" means that you are trying to sing something that you are not allowed to sign, i.e. not an official ECS release. This is probably the reason for your "Unsupported key system" error above as well, since there is not actually a Widevine CDM available.

Are you perhaps using a packager like `electron-builder`? In that case you need to provide a mirror correctly or it will use a stock Electron release to package your app, which would result in an error like the above. Check this FAQ out: https://github.com/castlabs/electron-releases/wiki/FAQ#how-can-i-use-electron-builder-with-ecs

**Comment by pnegahdar** [comment]
Works! Thanks for all the help. A few notes for anyone else: 

1) If using electron-builder you must also set the `electronVersion` attribute:

```
    "build": {
        "electronVersion": "11.4.0-wvvmp",
        "electronDownload": {
            "mirror": "https://github.com/castlabs/electron-releases/releases/download/v"
        },
}
```

2) The command `python3 -m castlabs_evs.vmp sign-pkg path/to/package-directroy` can exit with a zero status code when there was actually an error

Thanks for all the help!

**Comment by khwaaj** [comment]
@pnegahdar, I'm glad you got it working!

About (2), the signing script should not exit with a zero exit code in case of failure, if it does there is an issue somewhere. In the code you use above you would need the check `signEvs.status` instead of `signEvs.error`, I believe.

Please let me know if you still see any cases where an unexpected status code is returned from the script so that I can take a look at it!

**Comment by pnegahdar** [comment]
Ah, I probably read the node docs on child_process incorrectly. 

Thanks again for all the help!
